### ISSUE TITLE
Spheal is not unique from Speal w Holiday Costume

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#105]
when I select Spheal w Holiday Costume, Spheal also gets selected upon reload

Also, technically Spheal, Sealeo and Walrein are not released yet--only holiday costume Spheal is available

**Comment by BartmanEH** [comment]
pre-release schedule Spheal family for Jan. 1, 2022

**Comment by Rplus** [comment]
So, could we get shiny Spheal family now?

**Comment by BartmanEH** [comment]
Historically, any time a costumed Pokémon was released as shiny first for an event, it's non-costumed version was available when the event ended. Blitzle is a recent example. There's no reason to believe Spheal is any different. Will be the same for Hoothoot after this New Years event.
