### ISSUE TITLE
Litleo and Espurr families please

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#111]

**Comment by BartmanEH** [comment]
thank you.

I'm curious, you've added two(?) gender specific graphics now; Pyroar and Meowstic. What about other gender Pokemon with significant differences? Heracross, Hippowdon, Garchomp come to mind. Are you just doing Kalos and newer?

**Comment by Rplus** [comment]
I am not sure it will be a good idea or not if we add all gender specific.
I think we would discuss on #41 ~
