### ISSUE TITLE
Mega aerodactyl is missing

### ISSUE THREAD

**Issue by Duaneuk** [Rplus/Pokemon-shiny#113]
Mega aerodactyl is missing

**Comment by Duaneuk** [comment]
Guessing it won’t be added then. Makes a mockery of the whole list

**Comment by YesThatAllen** [comment]
The 'mon was added. You might try clearing your caches.

![2022-02-21_11-16-02](https://user-images.githubusercontent.com/2879972/155001194-827a41e3-febb-4829-88a8-1c67064b80ba.png)

**Comment by Duaneuk** [comment]
Done that on 2 devices and still not showing

**Comment by Rplus** [comment]
If you use leekduck website, just mail to leekduck for updating.
