### ISSUE TITLE
Pikachu wearing Okinawan kariyushi shirt

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#121]
https://www.leekduck.com/events/shiny-corsola-okinawa-shirt-pikachu/
Gonna be a while before I can get this one but it is technically released.

**Comment by Duaneuk** [comment]
It needs adding though if you want this list to be correct. Same with cottonee and tornadus

**Comment by BartmanEH** [comment]
> It needs adding though if you want this list to be correct. Same with cottonee and tornadus

those were added as well in the quoted release

**Comment by Duaneuk** [comment]
So the delay is down to leekduck again?

**Comment by Duaneuk** [comment]
I’ll use this instead of the leekduck version.

**Comment by Duaneuk** [comment]
How come the link above show 729 but leekduck has 730?

**Comment by BartmanEH** [comment]
RPlus sometimes needs a reminder to add a shiny. Today shiny Thundurus just came out :-)

**Comment by Duaneuk** [comment]
It’s unusual for leekduck to be up to date but not you

**Comment by Duaneuk** [comment]
Please can it be added to the rplus link? I don’t use leekduck anymore

Thanks

**Comment by BartmanEH** [comment]
I opened a new case for it:
[https://github.com/Rplus/Pokemon-shiny/issues/128](https://github.com/Rplus/Pokemon-shiny/issues/128)
