### ISSUE TITLE
Thundurus (Therian Form) please!

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#128]

**Comment by Duaneuk** [comment]
How come it’s listed on leekduck (notorious for never being up to date) but not rplus?

**Comment by BartmanEH** [comment]
you get what you pay for ;-) Pretty sure @Rplus is doing this for fun, not as a business, so let's all chip in with gentle reminders. RPlus usually adds missing mons in response to issues like this within a day or two and then closes the issue.

**Comment by Rplus** [comment]
Sorry, I updated 3 days age.
https://github.com/Rplus/Pokemon-shiny/commit/70f1ca94b8a66800e9e320ec0261e6eae60dcbde
But it seems like that I forgot to deploy. XD

**Comment by Rplus** [comment]
@Duaneuk @BartmanEH 
Thanks for notification!
I create a new issue(#129) for pre-released pokemon.
Hope that helps~

**Comment by Duaneuk** [comment]
It’s not pre-released. It came out almost a week ago.

**Comment by BartmanEH** [comment]
@Duaneuk the new issue let's you report any upcoming shiny in advance of its release to give RPlus a heads up to try to avoid this issue in the future.

**Comment by Duaneuk** [comment]
Cool. Thanks
