### ISSUE TITLE
Pre-release shiny Pokemon notification

### ISSUE THREAD

**Issue by Rplus** [Rplus/Pokemon-shiny#129]
Recently, I'm not focus on pokemon go news always.
So, I think I will be late to  add some shiny pokemon.

But the config could set pre-release date.
e.g. https://github.com/Rplus/Pokemon-shiny/commit/d147bb052bdf6b2ac17700a78b66c41ee6f31541
^ You could see I added this on 2021-12-01, but the release date is `"released_date": "2021/12/16"`

So, if you know which new shiny pokemon will be released, just comment in this issue! I'll add them in free time.

Thanks. 🙏

**Comment by BartmanEH** [comment]
Lopunny w Flower Crown, Togetic w Flower Crown and Togekiss w Flower Crown

**Comment by Duaneuk** [comment]
Is it me lol or has a normal shiny togekiss gone?!

**Comment by BartmanEH** [comment]
Cherubi family please

**Comment by BartmanEH** [comment]
Therian Forme Landorus tomorrow Apr. 26, 2022

**Comment by BartmanEH** [comment]
Mega Kangaskan (already released) and Mega Latios & Mega Latias May 3, 2022

**Comment by Duaneuk** [comment]
Please can we have the pikachu with Japanese balloons. Thanks

**Comment by BartmanEH** [comment]
> Please can we have the pikachu with Japanese balloons. Thanks

I don't think it's any different than Flying Pikachu released 2 years ago and already in the list.

**Comment by Duaneuk** [comment]
![Uploading D12A42F2-27CB-4718-845A-B0350219F64C.png…]()

**Comment by Duaneuk** [comment]
It has different coloured balloons
![Uploading F623700B-F1A2-4FA6-9D65-394F15F181B7.png…]()

**Comment by BartmanEH** [comment]
Hmm, seems to be another Okinawa regional. OK, let's see if @Rplus can dig up the sprite for it.

**Comment by BartmanEH** [comment]
Binacle family May 12

**Comment by BartmanEH** [comment]
Safari Zone, Seville (2 days ago): shiny Corphish family and shiny Unown S, E, V and I

**Comment by BartmanEH** [comment]
Binacle family is still missing

**Comment by BLameLance** [comment]
Shroomish Family is Missing. The released date was June 4, 2022.

**Comment by BartmanEH** [comment]
June 28: Pikachu wearing a Pokémon TCG hat

**Comment by BartmanEH** [comment]
Shiny Pansear and Foongus families will be released at Pokémon GO Fest 2022 Berlin July 1st, 2022.
Shiny Combee and Panpour families will be released at Pokémon GO Fest 2022 Seattle July 22, 2022.
Shiny Pansage and Swirlix families will be released at Pokémon GO Fest 2022 Sapporo August 5, 2022.

**Comment by BartmanEH** [comment]
July 6, 2022: GO Fest Berlin Ultra Unlock Event:
Charmeleon & Charizard w Party Hat (i.e. Charmander w Party Hat family)
Pikachu w Cake Costume
Pansear family (global release)

**Comment by BartmanEH** [comment]
@Rplus ? Can you add the above please?

**Comment by BartmanEH** [comment]
Snorlax w Top Hat was released GO Fest Berlin

**Comment by BartmanEH** [comment]
Venipede family Aug. 10, 2022

**Comment by BartmanEH** [comment]
@Rplus? Venipede family and Hisuian Braviary are missing!

**Comment by Rplus** [comment]
Okay, I update issue template. Please report that with new issue. Thanks

**Comment by BartmanEH** [comment]
so you don't want pre-release help anymore?

October 20th, 2022 - Shiny Noibat family and Galarian Yamask family will be released at the start of the first part of [Halloween 2022](https://pokemongo.fandom.com/wiki/Halloween_2022).

Mega Banette as well.
