### ISSUE TITLE
Include sex/variant options

### ISSUE THREAD

**Issue by dgl3906464** [Rplus/Pokemon-shiny#13]
Can we add toggle options for sexes and/or variant types?
For example, some people don't care if their pikachu is hatted or not, and others are trying for Noah's Box (male and female of each), and EVENTUALLY shiny unown will arrive, and 26 (or so) extra variants on the image isn't what I'm hoping to see on a checklist.

**Comment by Rplus** [comment]
The logic will be more complex after adding gender switcher.
I think create a new page for different gender is a good idea.
  > e.g.
  > ♂: https://rplus.github.io/Pokemon-shiny/?dex=5-6-7&nickname=Someone+♂
  > ♀: https://rplus.github.io/Pokemon-shiny/?dex=5-6-7&nickname=Someone+♀

Or like this?
https://godex.online/gender

And I know there is another issue: some pokemon without gender.
Waht do you think?

**Comment by dgl3906464** [comment]
gender shouldn't be bad - there's male percent, female percent, and
genderless percent in the master file.
forms are also listed - the alolan and unown, etc (but you have those
already)
the various costumes are NOT (but again, you have those already)

if i had to pick how to display them, maybe just separate checkboxes for
each available sex across the top of the existing box (forms and costumes
as separate entries, but sexes just as checkboxes)? in terms of the
highlight mechanic you've got, i'm not sure how to display that well,
though. maybe instead of a checkbox, border the male/female/genderless
(just a circle) symbols and make them selectable like the mon's box but
inset? behaviorally, you could go bananas with that, but i think that would
get too complex real quick and wouldn't be worth it unless you were just
bored (auto-select for genderless, parent-select if male or female is
picked, 3 form highlighting for partial and full selection, etc etc)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
