### ISSUE TITLE
Cowboy Hat Snorlax automatically "owned"

### ISSUE THREAD

**Issue by damon150196** [Rplus/Pokemon-shiny#141]
![Screenshot 2022-08-04 at 11-41-17 Shiny Checklist - Leek Duck Pokémon GO News and Resources](https://user-images.githubusercontent.com/34349373/182816408-d3f996c0-7808-42ab-98e3-06c1a93fa638.png)

I have a normal shiny snorlax before go fest added to checklist, After go fest snorlax with hat was automatically added as owned. 
Unchecking this and saving changes don't work. After refreshing the page snorlax is checked.

**Comment by Rplus** [comment]
I can't reproduce this issue.
Please ensure you use my site instead of leekduck's site.
