### ISSUE TITLE
upcoming Fashion Week 2022

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#149]
It is super helpful if you could paste the shiny pokemon url from pokeminers website.
e.q. https://pokeminers.com/gmexplore/#Pikachu_Copy_2019

https://pokemongolive.com/en/post/fashion-week-2022/
September 27, 2022
Absol w Fashionable Costume | 359
Diglet w Fashionable Costume | 50
Dugtrio w Fashionable Costume | 51
Toxicroak w Fashionable Costume | 454
Yveltal | 717 | 
![image](https://user-images.githubusercontent.com/6135879/191516470-5a61561a-7a08-4b56-83a4-cb7c6616deba.png)
Furfrou (Natural Form) | 676

I don't think any of the other Furfrou Trims will be shiny (but this is just my guess) [despite this infographic](https://twitter.com/LEGENDSLima/status/1572320449958125569/photo/1)

I tried to search pokeminers website for these new types. I just can't find most of them.

**Comment by BartmanEH** [comment]
There are confirmed reports that shiny Furfrou can be form-changed into all the other shiny forms.

**Comment by Rplus** [comment]
There are too much Furfrou form.
And it could be changed. I don't think it is meaningful.

**Comment by BartmanEH** [comment]
well Furfrou shiny rate is boosted and I know people with more than one shiny. I can see it as a long term goal to get them all kinda like Unown. I would vote to have all the Furfrou forms added.
