### ISSUE TITLE
Shiny List Resets

### ISSUE THREAD

**Issue by NukeWorker** [Rplus/Pokemon-shiny#150]
I read about an iOS user who mentioned that their shiny list gets reset every few months.

I use Firefox on Windows 10, and mine gets reset every few months as well, so its not exclusive to iOS.

Any tips would be appreciated.

**Comment by BartmanEH** [comment]
I use the Get Short URL feature:
<img width="184" alt="Screen Shot 2022-10-02 at 8 21 58 AM" src="https://user-images.githubusercontent.com/6135879/193453661-b872c861-ba0d-4ed3-9ab1-1c7bb4753de6.png">
and then save this as a bookmark. 100% reliable way to save your list.

**Comment by Rplus** [comment]
Same with #92
