### ISSUE TITLE
missing Spritzee family and Unown D, P and Y

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#151]
> I don't play Pokemon GO every day now.
> So, I will miss lots of news about new event.
> It will be super nice if you could provide more information about new shiny pokemon.

1. shiny pokemon (name? family? pokedex id?)
2. release date.
3. shiny image.

It is super helpful if you could paste the shiny pokemon url from pokeminers website.
e.q. https://pokeminers.com/gmexplore/#Pikachu_Copy_2019

You could delete all of above after you read them to create a new issue.Thanks~

**Comment by NukeWorker** [comment]
https://pokeminers.com/gmexplore/#Unown
                        "form": "UNOWN_Y",
                        "assetBundleValue": 35

**Comment by BLameLance** [comment]
Also Missing Unown D

**Comment by BartmanEH** [comment]
...and Unown P, so for Unown: D, P and Y are missing

**Comment by Rplus** [comment]
So, when did they be released?

**Comment by BartmanEH** [comment]
https://pokemongo.fandom.com/wiki/List_of_Shiny_Pok%C3%A9mon_release_dates#2022

September 23rd, 2022 - Shiny Y Unown, Spritzee and Aromatisse were released at the start of Pokémon GO Safari Zone Goyang.
August 27th, 2022 - Shiny P and X Unown, Munna and Musharna were released at the start of Pokémon GO Fest 2022 Finale.
August 17th, 2022 - Shiny D and N Unown were released at the start of Pokémon World Championships 2022.

P.S. you're early on Finneon family: October 21st, 2022 - Shiny Finneon and Lumineon will be released at the start of Pokémon GO Safari Zone New Taipei City 2022.

**Comment by Rplus** [comment]
For Fruit shirt Pikachu, I need for PokeMiner to get the special style image at first.

**Comment by BartmanEH** [comment]
> For Fruit shirt Pikachu, I need for PokeMiner to get the special style image at first.

I think it's here:
https://pokeminers.com/gmexplore/#Pikachu_Tshirt_01
