### ISSUE TITLE
Miss Shiny: Mega Alakazam & Mega Aggron

### ISSUE THREAD

**Issue by psauriol637** [Rplus/Pokemon-shiny#154]
1. Mega Alakazam - Abra Family - ID 065
2. Release Date: 9/6/22
3. https://pokeminers.com/gmexplore/#Alakazam

1. Mega Aggron - Aron Family - ID 306
2. Release Date: 9/16/22
3. https://pokeminers.com/gmexplore/#Aggron

**Comment by Rplus** [comment]
49e4f2e907754e5b4f1ec4ae2488b80e6b21d96d
8a9f08d3c70cbac4bdba282befb4d4a924aca7b3
