### ISSUE TITLE
missing now or soon: current event and next Safari Zone

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#161]
[The Greedy Gluttons event, November 9, 2022](https://pokemongolive.com/en/post/greedy-gluttons/)
[Munchlax](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm446.s.icon.png)

[Team GO Rocket takeover, November 14, 2022](https://pokemongolive.com/en/post/greedy-gluttons/)
[Pawniard](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm624.s.icon.png)

[Pokémon GO Safari Zone at Gardens by the Bay, October 24, 2022](https://pokemongolive.com/en/post/pokemon-go-safari-zone-singapore/)
[Pikachu w purple T-shirt (Flower)](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm25.fTSHIRT_02.s.icon.png)
[Pikachu, Flying w Purple Balloons](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm25.fFLYING_02.g2.s.icon.png)
[Purrloin](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm509.s.icon.png)
[Liepard](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm510.s.icon.png)

**Comment by K0STYURIK** [comment]
Between Munchlax and Pawniard/Bisharp there was also Ursaluna shiny release on Teddiursa Community Day

**Comment by BartmanEH** [comment]
@Rplus help!

**Comment by Evillunte** [comment]
I hope the last one coming soon on the checklist.

Use the checklist everyday, for a very long tine, years,so very sad the update is begin to lag
