### ISSUE TITLE
Miss Shiny: [pm name]

### ISSUE THREAD

**Issue by Evillunte** [Rplus/Pokemon-shiny#162]
> I don't play Pokemon GO every day now.
> So, I will miss lots of news about new event.
> It will be super nice if you could provide more information about new shiny pokemon.

1. shiny pokemon (name? family? pokedex id?)
2. release date.
3. shiny image.

It is super helpful if you could paste the shiny pokemon url from pokeminers website.
e.q. https://pokeminers.com/gmexplore/#Pikachu_Copy_2019

You could delete all of above after you read them to create a new issue.Thanks~

**Comment by Evillunte** [comment]
Will the list be updated soon ....?
Missing alot. New pika shirt and ballon. Purloin and evolution,munchlax,pawniard, 3* duskull with flower.. the new full moon teddi evolution.

And the two pumpkaboo without hat is wrong and not out

**Comment by Evillunte** [comment]
And could we get all 4 size of the pumpkaboo and the evolution on the list

**Comment by brunohmg89** [comment]
Hello..

I'm waiting for the update of the new shiny pokemons ..

**Comment by Evillunte** [comment]
Anything i can help you with ...? Missing a few from the last month ... But
i font know what is coming next

tor. 1. dec. 2022 12.33 skrev brunohmg89 ***@***.***>:

**Comment by brunohmg89** [comment]
Yea..

I look forward to updating my list, if you need help just show me where I open the PR to add the shiny new pokemons.

Missing all those you commented above and shedninja, the new castform and Mr. "Rime" of special research.

**Comment by Rplus** [comment]
Write down current title and description.
