### ISSUE TITLE
Pumpkaboo and Gourgeist names

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#166]
The Pumpkaboo and Gourgeist names should be changed to reflect the sizes as they are noted in the app.

Pumpkaboo(S) → Pumpkaboo small (XS)
Pumpkaboo → Pumpkaboo average ()
Pumpkaboo(L) → Pumpkaboo large (XL)
Pumpkaboo(XL) → Pumpkaboo super (XXL)
Gourgeist(S) → Gourgeist small (XS)
Gourgeist → Gourgeist average ()
Gourgeist(L) → Gourgeist large (XL)
Gourgeist(XL) → Gourgeist super (XXL)

**Comment by Rplus** [comment]
* [ ] Pumpkaboo(S) → Pumpkaboo small (XS)
* [ ] Pumpkaboo → Pumpkaboo average ()
* [ ] Pumpkaboo(L) → Pumpkaboo large (XL)
* [ ] Pumpkaboo(XL) → Pumpkaboo super (XXL)
* [ ] Gourgeist(S) → Gourgeist small (XS)
* [ ] Gourgeist → Gourgeist average ()
* [ ] Gourgeist(L) → Gourgeist large (XL)
* [ ] Gourgeist(XL) → Gourgeist super (XXL)

**Comment by BartmanEH** [comment]
Pumpkaboo (xS) should be Pumpkaboo (XS)
and
Gourgeist (xS) should be Gourgeist (XS)
