### ISSUE TITLE
New shiny

### ISSUE THREAD

**Issue by Evillunte** [Rplus/Pokemon-shiny#167]
New shiny ....
712 bergmite and evolution (is out) https://pokeminers.com/gmexplore/#Bergmite

Avalugg hisuian (24.dec)
https://pokeminers.com/gmexplore/#Avalugg_Hisuian

The evolution of event cubchoo (coming 23.dec)
https://pokeminers.com/gmexplore/#Cubchoo_Winter_2020

A new hat to the Eevee and the family (from 23.dec)
(Cant find the link to this one)

**Comment by Evillunte** [comment]
![FB_IMG_1671573991644](https://user-images.githubusercontent.com/119182614/208783189-a7ef2d32-90c3-4221-8c0d-78b143073903.jpg)

**Comment by Evillunte** [comment]
@Rplus 

D.31 dec. 
New Pikachu with Hat
Event hoothoot, can be evolved

![FB_IMG_1671745630592](https://user-images.githubusercontent.com/119182614/209232774-a5b69284-4c2f-4a87-adc8-d724c8b213e8.jpg)

**Comment by Rplus** [comment]
Could you help to coleect tha avatar image?
I don't play this game now.

**Comment by Evillunte** [comment]
Im not sure there to find the avatar image.

**Comment by Rplus** [comment]
Okay...
ps: Do not ping me in normal case.

**Comment by Evillunte** [comment]
And normal case is new shiny? Understood.

If i know there to find the avatar , i would love to link to them. Try to link to some from pokeminers

**Comment by Evillunte** [comment]
https://pokemongolive.com/post/new-years-2023/

**Comment by Evillunte** [comment]
Can you use this?

https://pokemongolive.com/post/winter-holiday-part-2-2022/

**Comment by Evillunte** [comment]
https://pokemongolive.com/post/community-january-2023-chespin/

**Comment by BartmanEH** [comment]
Holiday Eevee family:
Eevee
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm133.cHOLIDAY_2022.g2.s.icon.png

Vaporeon
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm134.cHOLIDAY_2022.s.icon.png

Jolteon
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm135.cHOLIDAY_2022.s.icon.png

Flareon:
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm136.cHOLIDAY_2022.s.icon.png

Espeon
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm196.cHOLIDAY_2022.s.icon.png

Umbreon
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm197.cHOLIDAY_2022.s.icon.png

Leafeon
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm470.cHOLIDAY_2022.s.icon.png

Glaceon
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm471.cHOLIDAY_2022.s.icon.png

Sylveon
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm700.cHOLIDAY_2022.s.icon.png

**Comment by Evillunte** [comment]
Do you have the image for chespin also?

Or can you guide me there to find them?

**Comment by BartmanEH** [comment]
Here's what I do; I navigate to this page:
[https://github.com/PokeMiners/pogo_assets/find/master](https://github.com/PokeMiners/pogo_assets/find/master)
click the "Go to file" button and in the resulting search address bar enter this:
Images/Pokemon - 256x256/Addressable Assets/pm[pokedex]
where [pokedex] is the pokedex index number of the pokemon of interest. For Chespin it's 650 so enter this:
Images/Pokemon - 256x256/Addressable Assets/pm650
and you'll see a list of all the available sprites for Chespin. Find the right one with a ".s." in the filename for shiny and get click to see the sprite and copy the URL:

Chespin
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm650.s.icon.png

Quilladin
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm651.s.icon.png

Chesnaught
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm652.s.icon.png

**Comment by Rplus** [comment]
Sorry for late! Thanks for your help!
Hope you have a good new year with shiny pokemon~


PS:
It will be helpful to follow syntax with the issue template that you could see it when you create a new issue.
Only 3 points:
* pokedex id (number) & name
* release date
* if possible, pokemon page on pokeminers or shiny image url(this will be super nice)

and it is good if there is an official event page
