### ISSUE TITLE
"Get short url" not working

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#168]
when you press the "Get short url" button, nothing happens.

**Comment by Rplus** [comment]
https://api.allorigins.win/ is down now.
This is a free service for get short url.
Try again later, or just save the original / long link.
![image](https://user-images.githubusercontent.com/1808835/210253068-18591944-a662-45b6-941c-170ed59eac98.png)

**Comment by BartmanEH** [comment]
the original/long link is no longer is saveable: because it's >256 chars long maybe? even if I manually copy the link and manually use TinyURL it doesn't work.

**Comment by Rplus** [comment]
What's your device when you can not bookemark the link? 
computer or phone?

**Comment by BartmanEH** [comment]
as of this morning, it's working again. "Get short url" button is working and the shortened URLs are working for my >2000 char URLs.
