### ISSUE TITLE
New shiny

### ISSUE THREAD

**Issue by Evillunte** [Rplus/Pokemon-shiny#170]
Chespin #650 (release 7. Januar 2023, community day)
https://pokeminers.com/gmexplore/#Chespin

Quilladin #651 release 7 januar - community day
https://pokeminers.com/gmexplore/#Quilladin

Chesnaught #652 (7. Jan. 2023)
https://pokeminers.com/gmexplore/#Chesnaugh

Dedenne #702 (release 10. Januar)
https://pokeminers.com/gmexplore/#Dedenne

Mega salamence #373 (release 10. Jan 2023)
 (cant pick the mega , but it is showing under the salamence) 

https://pokeminers.com/gmexplore/#Salamence

**Comment by BartmanEH** [comment]
Chespin
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm650.s.icon.png

Quilladin
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm651.s.icon.png

Chesnaught
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm652.s.icon.png

Dedenne
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm702.s.icon.png

Salamence (Mega)
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm373.fMEGA.s.icon.png

**Comment by BartmanEH** [comment]
I’ve been exploring the source code a bit and it seems to me that the whole URL is not needed just the pokedex index like so:

Chespin (family)
pm650

Dedenne
pm702

Salamence (Mega)
pm373.fMEGA

Maybe @Rplus could confirm what the most convenient data format is that should be provided.

**Comment by Rplus** [comment]
Don't just use 'new shiny' as issue title.
Please just keyin pokemon name, thanks!

**Comment by Rplus** [comment]
@BartmanEH
Yes, that's what I need.
But I always need to check the image is exist.
