### ISSUE TITLE
Error on padStart: polyfill not working?

### ISSUE THREAD

**Issue by hkmaly** [Rplus/Pokemon-shiny#18]
Hello,
I've got following error browsing in Chrome 55.
```
Uncaught TypeError: (("" + (intermediate value)) + "").padStart is not a function
    at getImgUrl (https://leekduck.com/assets/shiny/script.js?v3:193:29)
```
padStart is since Chrome 57, but I noticed you are including some polyfill ... well, it's not working apparently. In fact the file is empty.

**Comment by hkmaly** [comment]
Maybe update from v2 to v3?

**Comment by Rplus** [comment]
Hi, @hkmaly 
Thanks for your feedback.
I just update to use v3, but I don't have chrome v55 to test it.
could you help to check?

**Comment by hkmaly** [comment]
Sorry to not answer earlier. Unfortunately, still error about padStart, although somewhere else:
Uncaught TypeError: (("" + (intermediate value)) + "").padStart is not a function
    at getImgUrl (script.js:304)
    at setTimeout (script.js:80)
Maybe padStart is not included in "default"?

**Comment by hkmaly** [comment]
Not sure if you tested it or was just optimistic but I can confirm that now it works. Thanks!
