### ISSUE TITLE
Old shiny Spinda patterns

### ISSUE THREAD

**Issue by MrPrunez** [Rplus/Pokemon-shiny#180]
The shiny Spinda patterns changed a long time ago (last year?) to match the non-shiny ones. The only exception is Spinda #9.

**Comment by BartmanEH** [comment]
Spinda #1
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm327.f00.s.icon.png

Spinda #2
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm327.f01.s.icon.png

Spinda #3
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm327.f02.s.icon.png

Spinda #4
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm327.f03.s.icon.png

Spinda #5
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm327.f04.s.icon.png

Spinda #6
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm327.f05.s.icon.png

Spinda #7
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm327.f06.s.icon.png

Spinda #8
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm327.f07.s.icon.png

Spinda #9
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm327.f08.s.icon.png
