### ISSUE TITLE
Miss: shiny frillish family,and tapu lele

### ISSUE THREAD

**Issue by Evillunte** [Rplus/Pokemon-shiny#181]
Tapu lele #786 
https://pokeminers.com/gmexplore/#Tapu_Lele

Miss frillish evolution/jellicent
https://pokeminers.com/gmexplore/#Jellicent

https://pokeminers.com/gmexplore/#Jellicent_Female

**Comment by BartmanEH** [comment]
Tapu Lele #786
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm786.s.icon.png

Jellicent (male)
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm593.s.icon.png

Jellicent (female)
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm593.fFEMALE.s.icon.png

**Comment by Rplus** [comment]
When they were released?

**Comment by Evillunte** [comment]
Both in the shiny form, 8 januar

**Comment by BartmanEH** [comment]
Released February 8, 2023. I missed Jellicent in #178 :-(

**Comment by Evillunte** [comment]
Sorry write wrong. 8 februar. Release to the valentine event right now

**Comment by Evillunte** [comment]
BartmanEH, do you have the link to all the new release next week under the L.A event and later the global event?

**Comment by Evillunte** [comment]
![Screenshot_2023-02-09-13-40-51-479_com miui gallery](https://user-images.githubusercontent.com/119182614/217815500-5458f9f3-5db5-4a96-89ba-d4ace9e54340.jpg)

**Comment by Evillunte** [comment]
Las Vegas eventet ,18 februar.
And later globalt

https://gotour.pokemongolive.com/

![Screenshot_2023-02-09-13-43-15-651_com android chrome](https://user-images.githubusercontent.com/119182614/217816235-7c08f434-4343-478f-b186-4682d7337433.jpg)

**Comment by BartmanEH** [comment]
> ![Screenshot_2023-02-09-13-40-51-479_com miui gallery](https://user-images.githubusercontent.com/119182614/217815500-5458f9f3-5db5-4a96-89ba-d4ace9e54340.jpg)

these are covered in #176.

**Comment by BartmanEH** [comment]
> Las Vegas eventet ,18 februar. And later globalt
> 
> https://gotour.pokemongolive.com/
> 
> ![Screenshot_2023-02-09-13-43-15-651_com android chrome](https://user-images.githubusercontent.com/119182614/217816235-7c08f434-4343-478f-b186-4682d7337433.jpg)

I'll open a new case for the two costume Pikachu.
