### ISSUE TITLE
Miss Shiny: May's Hat Pikachu, Brendan's Hat Pikachu, Jellicent, Tapu Lele

### ISSUE THREAD

**Issue by thorvak** [Rplus/Pokemon-shiny#186]
English Name: 
25 May's Hat Pikachu
25 Brendan's Hat Pikachu
593 Jellicent M/F Family: Frillish
786 Tapu Lele

French name : 
25 Chapeau de Mai
25 Chapeau de Brendan
593 Moyade M/F Famille: Viskuse
786 Tokopiyon

Images:
[May's Hat Pikachu ](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon/Addressable%20Assets/pm25.cGOTOUR_2023_BANDANA.s.icon.png?raw=true)
[Brendan's Hat Pikachu](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon/Addressable%20Assets/pm25.cGOTOUR_2023_HAT.s.icon.png?raw=true)
[Jellicent Female](https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm593.fFEMALE.s.icon.png)
[Jellicent Male](https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm593.s.icon.png)
[Tapu Lele](https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm786.s.icon.png)

https://pokeminers.com/gmexplore/#Jellicent_Female
https://pokeminers.com/gmexplore/#Jellicent
https://pokeminers.com/gmexplore/#Tapu_Lele

**Comment by Evillunte** [comment]
The All Are on the list😉
(Edit the alle are on rplus shiny checklist, not on leekduck)

**Comment by thorvak** [comment]
> The All Are on the list😉 (Edit the all are on rplus shiny checklist, not on leekduck)

I don't understand, what shiny checklist ?

**Comment by thorvak** [comment]
> The All Are on the list😉 (Edit the all are on rplus shiny checklist, not on leekduck)

My bad I thought it was the same

**Comment by Evillunte** [comment]
Rplus make the list.
Leekduck copy the list from rplus,to his webside.

I have try to connect leekduck,and ask him for update. But no luck

**Comment by CodeWithMa** [comment]
leekduck is updated
