### ISSUE TITLE
Miss Shiny: galarian slowpoke,slowking and slowbro

### ISSUE THREAD

**Issue by Evillunte** [Rplus/Pokemon-shiny#187]
#79 Galarian slowpoke + family
Release to community day 18. Marts 2023

Images/Pokemon - 256x256/pokemon_icon_079_31_shiny.png

Images/Pokemon - 256x256/pokemon_icon_080_51_shiny.png

Images/Pokemon - 256x256/pokemon_icon_080_31_shiny.png

**Comment by Evillunte** [comment]
Images/Pokemon - 256x256/pokemon_icon_079_31_shiny.png

Images/Pokemon - 256x256/pokemon_icon_080_51_shiny.png

Images/Pokemon - 256x256/pokemon_icon_080_31_shiny.png

**Comment by BartmanEH** [comment]
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm79.fGALARIAN.s.icon.png

https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm80.fGALARIAN.s.icon.png

https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm199.fGALARIAN.s.icon.png
