### ISSUE TITLE
Miss Shiny: Tapu Bulu PM787

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#194]
April 17th, 2023 – Shiny [Tapu Bulu](https://pokemongo.fandom.com/wiki/Tapu_Bulu) was released

https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm787.s.icon.png

**Comment by Evillunte** [comment]
Can and will you find tapu Fini also. Release on Tuesday 9 may.

And can see in the shadow dex pinsir shadow is coming soon

**Comment by BartmanEH** [comment]
> Can and will you find tapu Fini also. Release on Tuesday 9 may.
[done](https://github.com/Rplus/Pokemon-shiny/issues/197)
> And can see in the shadow dex pinsir shadow is coming soon... (11 maj according to leek Duck)
we're not tracking shadow shinies with this tool--a decision that was made in the early days of shadow pokemon being introduced

**Comment by Evillunte** [comment]
Oh ok so not shadow pinsir. 
But tapu Fini

**Comment by Evillunte** [comment]
Dont know why i write shadow... Was thinking of mega😅🙈 but can see you have added, thx.
