### ISSUE TITLE
Miss Shiny: genesect shock 

### ISSUE THREAD

**Issue by Evillunte** [Rplus/Pokemon-shiny#195]
#649 genesect shock 

https://pokeminers.com/gmexplore/#Genesect_Shock

Realease:  2. May 2023

**Comment by BartmanEH** [comment]
[https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm649.fSHOCK.s.icon.png](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm649.fSHOCK.s.icon.png)
