### ISSUE TITLE
Miss Shiny: Tapu Fini, Ponyta family w Candela Accessory and Mega Pinsir

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#197]
released: May 11, 2023 for [A Valorous Hero event](https://pokemongolive.com/post/a-valorous-hero?hl=en)

Tapu Fini pm788
[https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm788.s.icon.png](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm788.s.icon.png)
![image](https://github.com/Rplus/Pokemon-shiny/assets/6135879/b20140bb-8589-4afd-a6da-6bfb13940163)

Ponyta with Candela Accessory pm77
image not in pokeminer asset database yet; here's a guess at what the link will be (will update when available):
[https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm77.cSPRING_2023_VALOR.s.icon.png](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm77.cSPRING_2023_VALOR.s.icon.png)
![image](https://github.com/Rplus/Pokemon-shiny/assets/6135879/2806c9af-74c1-45f7-ae99-dfd1320587a0)

Rapidash with Candela Accessory pm78
image not in pokeminer asset database yet; here's a guess at what the link will be (will update when available):
[https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm78.cSPRING_2023_VALOR.s.icon.png](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm78.cSPRING_2023_VALOR.s.icon.png)

Mega Pinsir pm
[https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm127.fMEGA.s.icon.png](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm127.fMEGA.s.icon.png)
![image](https://github.com/Rplus/Pokemon-shiny/assets/6135879/a65ceb00-2258-40e1-a14e-6e6e21e0eb5e)

**Comment by Rplus** [comment]
no ponyta, maybe open a new issue for that later.

**Comment by BartmanEH** [comment]
opening new issue for costume Ponyta family
