### ISSUE TITLE
Miss Shiny: Ponyta family with Candela Accessory pm77&78

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#201]
Ponyta with Candela Accessory pm77
image not in pokeminer asset database yet; here's a guess at what the link will be (will update when available):
[https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm77.cSPRING_2023_VALOR.s.icon.png](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm77.cSPRING_2023_VALOR.s.icon.png)

Rapidash with Candela Accessory pm78
image not in pokeminer asset database yet; here's a guess at what the link will be (will update when available):
[https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm78.cSPRING_2023_VALOR.s.icon.png](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm78.cSPRING_2023_VALOR.s.icon.png)

**Comment by BartmanEH** [comment]
I posted an issue at pokeminers repo and they responded that for now the assets can be pulled from Google Drive here:
[https://drive.google.com/drive/folders/1ICLqUUyxl986D-YTYwl79dX1ljBaUVNO](https://drive.google.com/drive/folders/1ICLqUUyxl986D-YTYwl79dX1ljBaUVNO)

Ponyta with Candela Accessory pm77
[https://drive.google.com/file/d/1KyP89r2W2lFPuYaTWLbvefvRzhl4Atra/edit](https://drive.google.com/file/d/1KyP89r2W2lFPuYaTWLbvefvRzhl4Atra/edit)

Rapidash with Candela Accessory pm78
[https://drive.google.com/file/d/1LnY1B4XqYDjjnY8Ta9z4938fx2e63t0F/edit](https://drive.google.com/file/d/1LnY1B4XqYDjjnY8Ta9z4938fx2e63t0F/edit)

**Comment by Rplus** [comment]
Do you know why we cannot get the image in github?

**Comment by Rplus** [comment]
Okay, I got that!
https://github.com/PokeMiners/pogo_assets/issues/42

**Comment by Rplus** [comment]
And then, I think we need to wait til the image is arrivable.
This tool use 256x256 image size.

**Comment by BartmanEH** [comment]
apparently the 256x256 version is in the .bundle files:
https://drive.google.com/file/d/1fTexEitJQ4qs3JFaT18_0g0-f9N4GZN2/view?usp=drive_link
https://drive.google.com/file/d/1fN1GsHAPaC9ADer77Lwva058pq4pEfod/view?usp=drive_link

I'm trying to figure out how to handle/open .bundle files. Will post my results here.

**Comment by BartmanEH** [comment]
The main repo was updated and the regular links work now

**Comment by Rplus** [comment]
relative with #197
