### ISSUE TITLE
Miss Shiny: Fomantis family pm753 & pm 754, and Nihilego pm793 & Pancham family pm674 & pm675

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#204]
released: Friday, June 16, 2023
[Solstice Horizons event](https://pokemongolive.com/post/solstice-horizons?hl=en)

Fomantis pm753:
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm753.s.icon.png

Lurantis pm754:
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm754.s.icon.png

Nihilego pm793:
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm793.s.icon.png

Pancham pm674:
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm674.s.icon.png

Pangoro on675:
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm675.s.icon.png

**Comment by Evillunte** [comment]
Need pancham too and family

**Comment by Evillunte** [comment]
Thx for link.💙. i cant figure it out on my phone, and have no computer .

The new turtle(cant remember the name) is out in shiny in raid and research.

And later this months two new Pikachu (ballon and shirt) is coming
And all the go fest shiny

**Comment by Evillunte** [comment]
![Screenshot_2023-06-24-08-54-01-471_com facebook katana](https://github.com/Rplus/Pokemon-shiny/assets/119182614/417595ba-2a3f-4aae-91ac-fd71dcd93008)

![received_1172004356984053](https://github.com/Rplus/Pokemon-shiny/assets/119182614/c4d9b386-a2d5-4e46-8e9d-b6be75b48066)

**Comment by BartmanEH** [comment]
Ugh… 20 new links to dig up. I’ll get to it eventually.

**Comment by Evillunte** [comment]
You dont have to... 😅  sorry for making you work

**Comment by BartmanEH** [comment]
There’s actually even more. Mega Rayquaza, Unown !, Pikachu wearing an amethyst crown…

**Comment by Evillunte** [comment]
Yes you correct, and theres 4-5 Pikachu amatyst,  mega tyranitar is also in the pokedex.

**Comment by BartmanEH** [comment]
@Rplus I've made new issues for all new shinies known to be coming in August. We're also behind on already released ones by a month. Can you provide an update for us please?
