### ISSUE TITLE
Miss Shiny: pm25 Pikachu wearing a blue shirt (Citrus) & pm25 Flying Pikachu with orange balloons

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#207]
[Air Adventures collaboration event](https://pokemongolive.com/events/airadventures-jejuisland): July 28, 2023

pm25 Pikachu wearing a blue shirt (Citrus):
https://pokeminers.com/gmexplore/#Pikachu_Jeju
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm25.fJEJU.s.icon.png
![image](https://github.com/Rplus/Pokemon-shiny/assets/6135879/64ae7192-98ee-4cb0-9878-e254e78d14c9)

pm25 Flying Pikachu with orange balloons:
Asset not in the main Pokeminer GitHub yet. Expected URL to monitor based on [pokeminer web link](https://pokeminers.com/gmexplore/#Pikachu_Flying_03):
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm25.fFLYING_03.s.icon.png

Temporary location in the PokeMiner Scratch folder:
https://drive.google.com/uc?id=1P-tehyNsdn-ChsprhPkUWcbOYrFHq4xc&export=download
![image](https://drive.google.com/uc?id=1P-tehyNsdn-ChsprhPkUWcbOYrFHq4xc&export=view)

**Comment by BartmanEH** [comment]
added link to 256x256 Flying Pikachu with Orange Balloons

**Comment by Rplus** [comment]
use another image?

**Comment by BartmanEH** [comment]
something is wrong with the web based database:
https://pokeminers.com/gmexplore/#Pikachu_Flying_03
which shows
![image](https://github.com/Rplus/Pokemon-shiny/assets/6135879/ab059407-3367-44c8-a2bf-055d02fd1fab)

**Comment by Evillunte** [comment]
The ballon is missing on the checklist

**Comment by BartmanEH** [comment]
> The ballon is missing on the checklist

That's why this issue is still open--because the image is not in pokeminer main database yet

**Comment by Evillunte** [comment]
Can er be sure to keep getting the image from pokeminer,then they have annonce theres soft shutdown..?

**Comment by Evillunte** [comment]
![Screenshot_2023-07-30-07-58-45-806_com twitter android](https://github.com/Rplus/Pokemon-shiny/assets/119182614/97990c55-1e07-4a2b-a96d-24d25b2148e2)

**Comment by BartmanEH** [comment]
> pm25 Flying Pikachu with orange balloons: Asset not in the main Pokeminer GitHub yet. Expected URL to monitor based on [pokeminer web link](https://pokeminers.com/gmexplore/#Pikachu_Flying_03): https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm25.fFLYING_03.s.icon.png

I made a [Pull Request](https://github.com/PokeMiners/pogo_assets/issues/43#issuecomment-1659399115) and got this image added to Pokeminer database.

**Comment by BartmanEH** [comment]
now that this image is available in new location, can you add it please?
