### ISSUE TITLE
Display a locked shiny pokémon

### ISSUE THREAD

**Issue by GiuseppeZ88** [Rplus/Pokemon-shiny#208]
Is it possible to display a shiny pokemon that will be released in future event? So it will be shown in the page but it will be unselectable...

I can specify the following parameters: "released_date" or "shiny_released" but I am not able to found what I'm searching for...

Can you help me?

Thanks, anyway thanks for your precious work! :)

**Comment by Rplus** [comment]
It will be shown automatically when the day comes.

If you want to check that in dev mode,
1. you could change the `today` in https://github.com/Rplus/Pokemon-shiny/blob/master/src/pms.js#L2
2. you could set a lower year of `released_date` in `pm.json`, but you have to remember to reset that after you checked the image in dev mode.

**Comment by Rplus** [comment]
If this issue is an enhancemonet, just re-open this one.
But I think I will not do this feature to show a non-released pm, it is a variable until it is released.
