### ISSUE TITLE
Miss Shiny: pm143 Snorlax with Nightcap

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#211]
released July 15, 2023 for [Catching Some Z’s](https://pokemongolive.com/post/pokemon-sleep-pokemon-go-plus-plus-event?hl=en) event

Snorlax wearing Nightcap pm143
![image](https://drive.google.com/uc?id=1wp59lFup9oRGVY4pZ8T5Q37mBOJGRwBH&export=download)

Image not in main pokeminer github database yet. Will update this post when permanent pokeminer asset URL becomes available.

A guess at the URL is:
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm143.fSUMMER_2023.s.icon.png

Edit: my guess was wrong. Looks like it will be:
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm143.cNIGHTCAP.s.icon.png

**Comment by BartmanEH** [comment]
Is the link to the image not the right size? According to [this post](https://github.com/PokeMiners/pogo_assets/issues/42#issuecomment-1569359993), the [Texture2D folder](https://drive.google.com/drive/folders/1tr1qXgDMkK3C_uUqmfD3vLJ80r-vH1Ir) has 256x256 size images so I expected [this image](https://drive.google.com/file/d/1wp59lFup9oRGVY4pZ8T5Q37mBOJGRwBH/view?usp=drive_link) to be 256x256 and useable.

**Comment by Rplus** [comment]
I just want to use image from same site(github/pokeminers).

It will be terrible to use a google drive photo.
I'm not sure it's always reachable, and the json file will be bigger than expected.

**Comment by BartmanEH** [comment]
OK, I think I understand--the tool uses a hard coded prefix for the image path which is the main pokeminer github database.

**Comment by Rplus** [comment]
Will the image file name be `pm143.cNIGHTCAP.s.icon.png`?

https://drive.google.com/uc?id=1wp59lFup9oRGVY4pZ8T5Q37mBOJGRwBH

When I paste the url of G-drive path, it will show the file name:
![image](https://github.com/Rplus/Pokemon-shiny/assets/1808835/78291822-3250-4e30-aa80-9ffac7734458)

**Comment by BartmanEH** [comment]
Yes, that’s correct. That’s the filename already in the scratch folder:
![image](https://github.com/Rplus/Pokemon-shiny/assets/6135879/1273cb7e-f01a-4813-85fa-960cbd3d17c4)

**Comment by BartmanEH** [comment]
I've made a [Pull Request](https://github.com/PokeMiners/pogo_assets/issues/43) to get this image into pokeminer database. It should be merged and this image should be available shortly.

**Comment by BartmanEH** [comment]
[https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm143.cNIGHTCAP.s.icon.png](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm143.cNIGHTCAP.s.icon.png)
This link is live now.
