### ISSUE TITLE
Miss Shiny: Mega Tyranitar pm248, Tyrunt family (pm696 & pm 697) and Amaura family (pm698 & pm699)

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#212]
released July 27, 2023 for [Adventure Week](https://pokemongolive.com/post/adventure-week-2023?hl=en) event

Mega Tyranitar pm248
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm248.fMEGA.s.icon.png
![image](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm248.fMEGA.s.icon.png?raw=true)

Tyrunt pm696
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm696.s.icon.png
![image](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm696.s.icon.png?raw=true)

Tyrantrum pm697
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm697.s.icon.png
![image](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm697.s.icon.png?raw=true)

Amaura pm698
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm698.s.icon.png
![image](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm698.s.icon.png?raw=true)

Araurus pm699
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm699.s.icon.png
![image](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm699.s.icon.png?raw=true)

**Comment by BartmanEH** [comment]
It seems Mega Tyranitar was released today, July 25, 2023

**Comment by Rplus** [comment]
Do you mean that released day has changed ?
![image](https://github.com/Rplus/Pokemon-shiny/assets/1808835/b8b83b92-fd43-460e-bc91-7bfb28f956eb)
