### ISSUE TITLE
Miss Shiny: Shellos, Gastrodon, Joltik, Galvantula, Goomy, Sliggoo, Goodra and Oranguru

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#215]
released August 27, 2023 for [Pokémon GO Fest 2023: Global](Pokémon GO Fest 2023: Global) event
Shellos East (pm422)
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm422.fEAST_SEA.s.icon.png?raw=true
![image](https://github.com/Rplus/Pokemon-shiny/assets/6135879/7d47aef1-205d-4a17-9f10-caad36390f5d)

Shellos West (pm422)
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm422.fWEST_SEA.s.icon.png?raw=true
![image](https://github.com/Rplus/Pokemon-shiny/assets/6135879/1cd2e4ba-f574-4a39-9b26-c9d5cf48cde5)

Gastrodon East (pm423)
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm423.fEAST_SEA.s.icon.png?raw=true
![image](https://github.com/Rplus/Pokemon-shiny/assets/6135879/bda497a1-67b9-416b-a6e3-bb0261416d06)

Gastrodon West
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm423.fWEST_SEA.s.icon.png?raw=true
![image](https://github.com/Rplus/Pokemon-shiny/assets/6135879/e742047a-98cd-43b7-ac44-ef1d7b1e847a)

Joltik (pm595)
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm595.s.icon.png?raw=true
![image](https://github.com/Rplus/Pokemon-shiny/assets/6135879/b14cd217-ec19-4f13-a67c-4ec9cee646c1)

Galvantula (pm596)
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm596.s.icon.png?raw=true
![image](https://github.com/Rplus/Pokemon-shiny/assets/6135879/571b02b4-e1c5-472b-8d1f-90d65d801e35)

Goomy (pm704)
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm704.s.icon.png?raw=true
![image](https://github.com/Rplus/Pokemon-shiny/assets/6135879/81796a5a-54fd-414a-8de9-bda972c2baee)

Sliggoo (pm705)
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm705.s.icon.png?raw=true
![image](https://github.com/Rplus/Pokemon-shiny/assets/6135879/9b4dd8a8-b0d2-4896-9578-5dab933e5b22)

Goodra (pm706)
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm706.s.icon.png?raw=true
![image](https://github.com/Rplus/Pokemon-shiny/assets/6135879/a194ea39-14a0-4184-8868-92df67e71526)

Oranguru (pm765)
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm765.s.icon.png?raw=true
![image](https://github.com/Rplus/Pokemon-shiny/assets/6135879/02879a24-3413-4e47-b9bd-db0bdf10dfbe)

**Comment by MelkyAir** [comment]
Should this issue be re-opened as they are not showing up in the latest drop?

**Comment by BartmanEH** [comment]
> Should this issue be re-opened as they are not showing up in the latest drop?

I looked at the source code--they are scheduled to be "released" tomorrow so easiest just wait one more day :-)
