### ISSUE TITLE
Miss Shiny : pumpkaboo and family without hat

### ISSUE THREAD

**Issue by Evillunte** [Rplus/Pokemon-shiny#223]
Leekduck shows that pumpkaboo can be shiny under the gofest event in London and Osaka. 
If thats true we miss them on the list.

1. shiny pokemon (pumpkaboo family, #710)
2. release date.: 4 aug 2023 go fest
3. shiny image:

https://pokeminers.com/gmexplore/#Pumpkaboo_Average
https://pokeminers.com/gmexplore/#Pumpkaboo_Large
https://pokeminers.com/gmexplore/#Pumpkaboo_Small
https://pokeminers.com/gmexplore/#Pumpkaboo_Super

And theres evolution 

![Screenshot_2023-08-04-07-53-24-961_com miui gallery](https://github.com/Rplus/Pokemon-shiny/assets/119182614/6006b63c-30c4-46dd-b205-3d1350769ceb)

**Comment by Evillunte** [comment]
Alright, i have now catch a pumpkaboo in shiny by my self. So they are out in shiny

**Comment by BartmanEH** [comment]
well let's add them all for now:

https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm710.fAVERAGE.s.icon.png

https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm710.fLARGE.s.icon.png

https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm710.fSMALL.s.icon.png

https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm710.fSUPER.s.icon.png

**Comment by Evillunte** [comment]
And you can evolve them...

**Comment by BartmanEH** [comment]
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm711.fAVERAGE.s.icon.png

https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm711.fLARGE.s.icon.png

https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm711.fSMALL.s.icon.png

https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm711.fSUPER.s.icon.png
