### ISSUE TITLE
Aerodactyl w Satchel: image is offset

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#224]
![Screen Shot 2023-08-09 at 2 29 11 PM](https://github.com/Rplus/Pokemon-shiny/assets/6135879/d3607c1c-3723-44e2-8d85-f4569587533a)
Here's what I see. It appears that the image is offset upwards?

**Comment by Rplus** [comment]
They come from different image folders (old / new), so they have different size and position
