### ISSUE TITLE
More status options for shiny status

### ISSUE THREAD

**Issue by YesThatAllen** [Rplus/Pokemon-shiny#24]
I have been trying to keep up with three URLs.. 
 - shiny's I have available for trade
 - shiny's I want more of
 - shiny's that I want as new.

I see now support has been added for Owns & Registered.

What do you think of these other status:

- Available to trade
- Registered
- Want, registered
- Want, unregistered
- Released (this would be the default, un-selected choice that newly released 'mon would fall to)

*Edit added `trying to keep up with`

**Comment by Rplus** [comment]
I think you need this one. :P  
https://rplus.github.io/pm-list/

**Comment by YesThatAllen** [comment]
BUT NO SHINIES THERE

**Comment by Rplus** [comment]
I don't think it is a good idea for put too many features or functions in the list.

If I have three types checklist, I just change the nickname input and then add three bookmarkets on the browser.
The nickname will identify the checklist type clearly.

![image](https://user-images.githubusercontent.com/1808835/56768270-800a3a80-67e0-11e9-84b5-97e76f962ed2.png)

**Comment by YesThatAllen** [comment]
Ok, I've updated my 4 lists.. 

Available for trade
Wish I could get more of (unregistered)
Wish I could get more of (registered)
My overall list.

I'd much rather have my overall list (registered & owned, as you have now) and add emoji for 🙏 on ones I'd like to get in trade, or 💸 for ones I have spare of. (or :take_my_money: but github doesn't support that ;-) )

If adding "have spare" "wish to get" next to any given 'mon image isn't in your worklist, feel free to close the issue.

**Comment by Rplus** [comment]
Thanks, that's an interesting idea to add emoji / tag.
But I think that needs to change the method of interaction.
It will be a huge task, and this tool will be named as "Shiny list"(not "checklist").

So, I mark this issue as wontfix now. :P
