### ISSUE TITLE
Shiny: pm762 name shows as "undefined"

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#243]
probably an issue with the PR I did but Bombirdier pm762 shows as "undefined":
<img width="139" alt="Screen Shot 2023-09-13 at 8 47 42 AM" src="https://github.com/Rplus/Pokemon-shiny/assets/6135879/e526863b-40f3-46ff-b464-24e272e635b9">

**Comment by Rplus** [comment]
First, I think the pokedex is 962.

There is still no name of new generation pokemon.
https://github.com/Rplus/Pokemon-shiny/blob/master/assets/name.json

**Comment by Rplus** [comment]
close by https://github.com/Rplus/Pokemon-shiny/commit/3d863c42d472eb939942311326a8d6699c4491f2

**Comment by BartmanEH** [comment]
> First, I think the pokedex is 962.

Ugh, you're right, my mistake. Sorry about that. I changed the issue title for the record.

Thanks for adding all the gen 9 names--I didn't even know about this file!
