### ISSUE TITLE
Add tag to Genesect

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#245]
Would it be possible to add a tag/letter to the Genesect which type it is, as it is very difficult to see it from the image alone?
N (Normal) 
S (Shock Drive)
B (Burn Drive)

And in the future also:
C ( Chill Drive)
D (Douse Drive)

**Comment by Evillunte** [comment]
Good idea

**Comment by BartmanEH** [comment]
I've created a pull request for this change. If I've done it correctly, RPlus will likely incorporate it

**Comment by BartmanEH** [comment]
I messed up the Pull Request. I have taken feedback from RPlus, closed previous faulty PR and made a new separate PR

**Comment by BartmanEH** [comment]
PR updated to use emoji suffix
