### ISSUE TITLE
Miss Shiny: Solosis family

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#246]
Solosis 
#577
21-09-2023
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm577.s.icon.png

Duosion
#578
21-09-2023
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm578.s.icon.png

Reuniclus
#579
21-09-2023
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm579.icon.png

**Comment by MelkyAir** [comment]
Added by @BartmanEH to https://rplus.github.io/
Still missing from https://leekduck.com/shiny/
There're actually a few mismatches now between the sites. Any way to get the missing data over to leekduck too?

**Comment by BartmanEH** [comment]
That's up to Leekduck.

**Comment by Rplus** [comment]
closed by #247
