### ISSUE TITLE
Miss Shiny: Grubbin family

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#248]
Grubbin
#736
23-09-2023
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm736.s.icon.png

Charjabug
#737
23-09-2023
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm737.s.icon.png

Vikavolt
#738
23-09-2023
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm738.s.icon.png

**Comment by BartmanEH** [comment]
Pull Request done

**Comment by BartmanEH** [comment]
I messed up the Pull Request. I have taken feedback from RPlus, closed previous faulty PR and made a new PR
