### ISSUE TITLE
show pokedex number?

### ISSUE THREAD

**Issue by YesThatAllen** [Rplus/Pokemon-shiny#25]
When I'm looking in my pokedex to see what i have/don't have, it'd be sweet to be able to see the pokedex number on this site.

Making it searchable like you did with pokemon names in #21 (thank you!) could be useful but may not be needed.

**Comment by Rplus** [comment]
There is pokedex in the title, you could hover it to see.
![image](https://user-images.githubusercontent.com/1808835/57605846-2785bc00-759a-11e9-9e40-97d06b6e02fc.png)
