### ISSUE TITLE
Miss Shiny: Hisuian Growlithe & Arcanine

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#252]
Hisuian Growlithe
ID 58 
release date: 27-09-2023
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm58.fHISUIAN.s.icon.png

Hisuian Arcanine
ID 59 
release date: 27-09-2023
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm59.fHISUIAN.s.icon.png

**Comment by BartmanEH** [comment]
addressed with this [PR](https://github.com/Rplus/Pokemon-shiny/pull/253)
