### ISSUE TITLE
Miss Shiny: [detective Pikachu and raichu, and slowpoke with detective hat

### ISSUE THREAD

**Issue by Evillunte** [Rplus/Pokemon-shiny#254]
1. shiny pokemon : Pikachu,raichu,slowpoke detective hat 
2. release date. = 5. Okt 2023
3. shiny image. Cant Find and link from my phone,sorry
![Screenshot_2023-10-03-09-52-46-21_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Rplus/Pokemon-shiny/assets/119182614/b6a035ef-7fdc-4ea4-b16b-b34be0021f47)

**Comment by BartmanEH** [comment]
so far I have been unsuccessful to locate these assets in pokeminer databases--doesn't seem to be in their scratch folder even

**Comment by Evillunte** [comment]
THX for looking

**Comment by BartmanEH** [comment]
Detective Pikachu family found. PR created: https://github.com/Rplus/Pokemon-shiny/pull/256

**Comment by BartmanEH** [comment]
@Rplus: the remaining slowpoke w hat asset hasn't been mined despite efforts on [pokeminer github](https://github.com/PokeMiners/pogo_assets/issues/56), I used the lower res image to transfer the cowboy hat onto the normal slowpoke shiny 256x256 image. The results are pretty good:
![pm79 cCOWBOYHATs icon](https://github.com/Rplus/Pokemon-shiny/assets/6135879/6e2bce72-eb9d-47e8-a46f-a29d7641f14b)

As this may become more and more of an issue going forward, is there some way we could use other image sources such as this?

**Comment by BartmanEH** [comment]
well it seems the asset was merged into pokeminer database by someone so I've done a PR #263 to add it.
