### ISSUE TITLE
Miss Shiny: Guzzlord

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#257]
Guzzlord
ID 799
Released: 06-10-2023
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm799.s.icon.png

**Comment by BartmanEH** [comment]
please add the source for evidence that the shiny variant is being released.

I don't see shiny Guzzlord mentioned in the official [blog](https://pokemongolive.com/post/greedy-gluttons/?hl=en)?

**Comment by MelkyAir** [comment]
I have it.. do you want a screen shot?

**Comment by MelkyAir** [comment]
![IMG-20231006-WA0001](https://github.com/Rplus/Pokemon-shiny/assets/142159643/b043a7bc-5095-41c5-88df-b5d82edea7fd)

**Comment by BartmanEH** [comment]
he he, congrats. I guess that's enough evidence :-)

**Comment by BartmanEH** [comment]
added via PR #260
