### ISSUE TITLE
Miss Shiny: Skiddo family

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#258]
Skiddo
ID 672
Released: 07-10-2023
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm672.s.icon.png

Gogoat
ID 673
Released: 07-10-2023
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm673.s.icon.png

**Comment by MelkyAir** [comment]
@BartmanEH Also the eevee with safari hat family, maybe you can find it in the pokeminers DB?

**Comment by BartmanEH** [comment]
Skiddo family added via [PR #259](https://github.com/Rplus/Pokemon-shiny/pull/259)

**Comment by BartmanEH** [comment]
> @BartmanEH Also the eevee with safari hat family, maybe you can find it in the pokeminers DB?

would you please make this a new issue--I don't think the assets are available yet but either way, easier to track as a separate issue
