### ISSUE TITLE
Miss Shiny: [cubone costume]

### ISSUE THREAD

**Issue by Evillunte** [Rplus/Pokemon-shiny#272]
> I don't play Pokemon GO every day now.

1. shiny pokemon : cubone halloween costume
2. release date. : 1. Nov
3. shiny image. Sorry cant figure out to find the image and link on my phone

https://pokeminers.com/gmexplore/#Pikachu_Copy_2019

**Comment by Evillunte** [comment]
![Uploading Screenshot_2023-10-26-09-19-46-00_92460851df6f172a4592fca41cc2d2e6.jpg…]()

**Comment by Evillunte** [comment]
![Screenshot_2023-10-26-09-19-46-00_92460851df6f172a4592fca41cc2d2e6](https://github.com/Rplus/Pokemon-shiny/assets/119182614/be72ff69-fa9c-4b64-a7fd-e368d2d9c9b3)

**Comment by MelkyAir** [comment]
@BartmanEH 

Cubone
https://github.com/PokeMiners/pogo_assets/blob/6ddfbe41886364d2c903967f727139aa11aa3cce/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm104.cFALL_2023.icon.png?raw=true

Marowak
https://github.com/PokeMiners/pogo_assets/blob/6ddfbe41886364d2c903967f727139aa11aa3cce/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm105.cFALL_2023.icon.png?raw=true

**Comment by BartmanEH** [comment]
created a PR to add these too

**Comment by Rplus** [comment]
> created a PR to add these too

You could just write down the PR number, that will help me to find this related issue~
#276
