### ISSUE TITLE
Miss Shiny: Paldean Wooper [pm194] and Clodsire [pm980]

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#273]
release date: November 5, 2023 for [Community Day](https://pokemongolive.com/post/communityday-november-2023-wooper/?hl=en)

assets not available yet so these will have to wait for a bit

**Comment by MelkyAir** [comment]
Clodsire

https://github.com/PokeMiners/pogo_assets/blob/6ddfbe41886364d2c903967f727139aa11aa3cce/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm980.s.icon.png?raw=true

Paldean Wooper

https://github.com/PokeMiners/pogo_assets/blob/6ddfbe41886364d2c903967f727139aa11aa3cce/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm194.fPALDEA.s.icon.png?raw=true

**Comment by BartmanEH** [comment]
made a PR to add these
