### ISSUE TITLE
Miss Shiny: genesect douse drive

### ISSUE THREAD

**Issue by Evillunte** [Rplus/Pokemon-shiny#277]
1. shiny pokemon : #649 genesect douce drive
2. release date. : 3 nov

https://pokeminers.com/gmexplore/#Genesect_Douse

![image](https://github.com/Rplus/Pokemon-shiny/assets/119182614/3fe7368f-7603-42cd-8226-05b1d174e61a)

**Comment by BartmanEH** [comment]
added via PR #278

**Comment by BartmanEH** [comment]
@Evillunte can you close this issue please?
