### ISSUE TITLE
Miss Shiny: pm445 Mega Garchomp

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#279]
placeholder; asset not available yet. expected to be [pm445.fMEGA](https://github.com/PokeMiners/pogo_assets/tree/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm445.fMEGA.s.icon.png)

**Comment by MelkyAir** [comment]
Mega Garchomp:
https://raw.githubusercontent.com/PokeMiners/pogo_assets/46f590629958683cb7770deec29d25fff004502d/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm445.fMEGA.s.icon.png

**Comment by BartmanEH** [comment]
PR #283
