### ISSUE TITLE
Is the detective Pikachu image wrong?

### ISSUE THREAD

**Issue by Evillunte** [Rplus/Pokemon-shiny#280]
Is the shiny image wrong. ?
Just open my costume dex and see 2 Pikachu detective and two detective raichu.

The old detective Pikachu ( was not out in shiny .
The new one we just had, was shiny, and it has a glass in the hand. (The old was without glass in the hand)

The image on the shiny checklist is without glass (dont know if there is a image with glass in the hand)

![IMG_20231106_153145](https://github.com/Rplus/Pokemon-shiny/assets/119182614/458f8c79-8032-430d-927b-10a83c22c1dc)

![Screenshot_2023-11-06-15-46-15-27_8a5f4726f7453c77b8d93615cedb556d](https://github.com/Rplus/Pokemon-shiny/assets/119182614/6fd64b3e-5452-421c-86e2-9aec5c01f2bc)

![Screenshot_2023-11-06-15-50-14-50_8a5f4726f7453c77b8d93615cedb556d](https://github.com/Rplus/Pokemon-shiny/assets/119182614/dbd2728f-54c4-4428-ab1b-259bd1dc9543)

**Comment by MelkyAir** [comment]
The sprites are the same, only the animation is different. It doesn't make a difference for the shiny list.
Was also discussed briefly in pokeminers issue: [https://github.com/PokeMiners/pogo_assets/issues/56](url)

**Comment by Evillunte** [comment]
Just thjourgt when niantic give them two different places in the dex , i couldd be a problem ,maybe later.

**Comment by Evillunte** [comment]
The link dont work.
Just think, when niantic give them two different places in the dex,it could give problem in the future

**Comment by BartmanEH** [comment]
> Is the shiny image wrong. ? Just open my costume dex and see 2 Pikachu detective and two detective raichu.
> 
> The old detective Pikachu ( was not out in shiny . The new one we just had, was shiny, and it has a glass in the hand. (The old was without glass in the hand)
> 
> The image on the shiny checklist is without glass (dont know if there is a image with glass in the hand)
> 
> ![IMG_20231106_153145](https://user-images.githubusercontent.com/119182614/280751323-458f8c79-8032-430d-927b-10a83c22c1dc.jpg)
> 
> ![Screenshot_2023-11-06-15-46-15-27_8a5f4726f7453c77b8d93615cedb556d](https://user-images.githubusercontent.com/119182614/280751365-6fd64b3e-5452-421c-86e2-9aec5c01f2bc.jpg)
> 
> ![Screenshot_2023-11-06-15-50-14-50_8a5f4726f7453c77b8d93615cedb556d](https://user-images.githubusercontent.com/119182614/280751428-dbd2728f-54c4-4428-ab1b-259bd1dc9543.jpg)

This must be some kind of bug in the game. I don't think it makes sense to add another copy to the checklist since you can't actually get the original in shiny anyway.

**Comment by Evillunte** [comment]
Like melkyair say, the animations is different on those two...
And The animations is being show both in your pokemon bag and in the dex.

Hope its a bug that both is in the event dex.
And niantic dont release the old in shiny also.
What would be a problem .

Wonder if there is  a image with the magnifying glass.?

**Comment by BartmanEH** [comment]
I still don't understand what you are suggesting we should do. With the new version, the magnifying glass only shows during animation. We don't show animations in the checklist, we show static image only. The static image asset doesn't have a magnifying glass. All this relates to the bug where Niantic forgot to turn on the shiny for the first release and the asset has been available all along. Since the original is not available, there's nothing to collect right now and nothing to be done in the checklist until something changes like they actually release the original or something.

**Comment by Evillunte** [comment]
Sorry my bad english, not good to write or talk it . In from Denmark.

 know we dont show animation in the checklist, but only image. but maybe there was a image with the magnifying glass.

I can understand on you last message there is not a image with the glass👍, so i close this.

( some people on google say detective was shortly out in shiny the first time, but it was a mistake from niantic,and the remove it again)

**Comment by BartmanEH** [comment]
I totally agree--pretty sure it was a mistake by Niantic. Don't worry about your English--it's perfectly adequate for our intentions here! I was just trying to understand if there was a real action we should take on this issue.

**Comment by Evillunte** [comment]
Thx...
Just wonder if a image of a Pikachu with magnifying glass was the best solution if its not was a bug from niantic. 
But there is no, so no problem...
