### ISSUE TITLE
Miss Shiny: fashion wooper and family, dragonite fashion]

### ISSUE THREAD

**Issue by Evillunte** [Rplus/Pokemon-shiny#281]
Release 15 nov. 
Wooper and evolution
Dragonite fashion

Sorry for the missing image

![FB_IMG_1699466702677](https://github.com/Rplus/Pokemon-shiny/assets/119182614/5761f5b9-b769-4961-bf0b-b614f2b5039f)

**Comment by BartmanEH** [comment]
PR #285

**Comment by Evillunte** [comment]
Shall i close?

**Comment by BartmanEH** [comment]
You're welcome to wait until you confirm they are successfully in the list which will be after RPlus merges my PR code and after the Nov. 15th--they won't show up until then. You have a choice, you can close after you see them, or close it now and open a new issue if you don't see them on or after the 15th (this is my preference).

**Comment by Rplus** [comment]
> You're welcome to wait until you confirm they are successfully in the list which will be after RPlus merges my PR code and after the Nov. 15th--they won't show up until then. You have a choice, you can close after you see them, or close it now and open a new issue if you don't see them on or after the 15th (this is my preference).

If you don't see the pm after the released day, it will be better to "re-open" this issue rather than open a new issue~

**Comment by BartmanEH** [comment]
> Shall i close?

so, yes, please close
