### ISSUE TITLE
Miss Shiny: Gothita family (15-11-2023)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#282]
Release date : 15-11-2023

Gothita
ID #574
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm574.s.icon.png

Gothorita
ID #575
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm575.s.icon.png

Gothitelle
ID #576
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm576.s.icon.png

**Comment by BartmanEH** [comment]
PR #284
