### ISSUE TITLE
Miss Shiny: Samurott Hisuian

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#287]
Samurott Hisuian
ID#503
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm503.fHISUIAN.s.icon.png
Release Dec 3rd

**Comment by BartmanEH** [comment]
PR #286

**Comment by BartmanEH** [comment]
I suggest leaving this open until we see it in list
