### ISSUE TITLE
Dragonite with a Fashionable Costume display style vertical offset

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#288]
New Fashion Week Dragonite is offset:
<img width="245" alt="Screenshot 2023-12-04 at 8 16 28 AM" src="https://github.com/Rplus/Pokemon-shiny/assets/6135879/753c4ecb-8517-40da-8eaa-15e4c1121295">

I'm not sure how to change the display style to match original Dragonite because original Dragonite doesn't have a style offset:
```
  {
    "dex": 149,
    "family": "Dratini",
    "released_date": "2018/02/24"
  },
  {
    "dex": 149,
    "family": "Dratini",
    "released_date": "2023/11/15",
    "isotope": "_f23",
    "aa_fn": "pm149.cFALL_2023"
  },
```

**Comment by BartmanEH** [comment]
@Rplus can you show me how to move this image please?

**Comment by BartmanEH** [comment]
@Rplus can you review my 3 pull requests please and maybe look at this issue please?

**Comment by Rplus** [comment]
Sorry for the late reply.

It needs set a style property to change position.
There are three types:
```
"style": "--w: 130%; --t: -20%; --l: 0%;",
```
* w: size
* t: top
* l: left

You can change the value in Browser devtool to preview the position.
![image](https://github.com/Rplus/Pokemon-shiny/assets/1808835/07d30f31-4ce2-4aac-90d0-c8479873907a)
