### ISSUE TITLE
Miss Shiny: Cryogonal (09-12-23)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#289]
Cryogonal
ID#615
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm615.s.icon.png
Release date: Dec 9th 2023

**Comment by MelkyAir** [comment]
Source: https://pokemongolive.com/post/catch-mastery-ice-2023?hl=en

**Comment by BartmanEH** [comment]
PR #292
