### ISSUE TITLE
Be able to save status

### ISSUE THREAD

**Issue by Rplus** [Rplus/Pokemon-shiny#29]
For PWA user, they cannot see url bar and cannot update bookmarklet in PWA page.
So, they will have some problem to update new shiny status.

Solution:

[save] => check storage
=> new? => save status
=> update? => udpate status
==> list all "saved titles"

It might be not a good idea for auto updating / saving status, that might overwrite old status.
Just look it as a bookmarklet

**Comment by domenicoblanco** [comment]
I'll try to do this tonight but really often it breaks the PWA as they're not supposed to be updated.
I'll let you know when I'll get some results

**Comment by Rplus** [comment]
@domenicoblanco Thanks for your help!
I had comment on #30.

In my plan, I will refactor this project with some framework at first, and add this feature later.

**Comment by domenicoblanco** [comment]
I just read your comment in #30 and I think it could be possible in the same way but with a possible sideNav. We could use a selector to create a "bookmarks list" and use the same trick of the localStorage but with more items.

As I read, the localStorage limit is 5MB and we're just saving URLs

**Comment by Rplus** [comment]
Yes, using a list to control is a good idea

**Comment by Rplus** [comment]
![image](https://user-images.githubusercontent.com/1808835/64414080-571a8000-d0c5-11e9-95d8-a86668829b99.png)
For the new version, there is a list for saved item. :P
