### ISSUE TITLE
Miss Shiny: Hisuian Sneasel family (05-12-23)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#290]
Sneasel Hisuian
ID#215
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm215.fHISUIAN.s.icon.png
Release date: Dec 5th 2023

Sneasler
ID#903
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm903.s.icon.png
Release date: Dec 5th 2023

**Comment by MelkyAir** [comment]
Source: https://pokemongolive.com/post/along-the-routes-2023?hl=en

**Comment by BartmanEH** [comment]
PR #293
