### ISSUE TITLE
Miss Shiny: Pikachu & Psyduck families wearing holiday attire (18-12-'23)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#295]
Pikachu wearing holiday attire
ID#25
https://raw.githubusercontent.com/PokeMiners/pogo_assets/d01ce17fa9b30fbf41b5cf73bdbb4be44dd0f1d7/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm25.cHOLIDAY_2023.s.icon.png

Raychu wearing holiday attire
ID#26
https://raw.githubusercontent.com/PokeMiners/pogo_assets/d01ce17fa9b30fbf41b5cf73bdbb4be44dd0f1d7/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm26.cHOLIDAY_2023.g2.s.icon.png

Psyduck wearing holiday attire
ID#54
https://github.com/PokeMiners/pogo_assets/blob/d01ce17fa9b30fbf41b5cf73bdbb4be44dd0f1d7/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm54.cHOLIDAY_2023.s.icon.png

Golduck wearing holiday attire.
ID#55
https://github.com/PokeMiners/pogo_assets/blob/d01ce17fa9b30fbf41b5cf73bdbb4be44dd0f1d7/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm55.cHOLIDAY_2023.s.icon.png

release date 18-12-2023

**Comment by BartmanEH** [comment]
I couldn't add it a few days ago because the assets weren't available yet. Added via PR #296

**Comment by Evillunte** [comment]
What about psyduck and evolution in the same event.

**Comment by MelkyAir** [comment]
It wasn't announced yet Dec 13th.. I'll open a new issue with the images for the vanillite and Psyduck

**Comment by Evillunte** [comment]
THX🙏👍🩵

**Comment by MelkyAir** [comment]
@BartmanEH The Psyduck is also released at the same time, as reward in the timed research. Could you add these as well please?

**Comment by BartmanEH** [comment]
with reluctance as it's another paywalled low probability shiny, added via PR #299

**Comment by BartmanEH** [comment]
> with reluctance as it's another paywalled low probability shiny, added via PR #299 

My bad. It's available in the wild. Yay!
