### ISSUE TITLE
Miss Shiny: wyrdeer

### ISSUE THREAD

**Issue by Evillunte** [Rplus/Pokemon-shiny#297]
1. shiny pokemon: wyrdeer
2. release date. 23. Dec
3. shiny image. ?? Cant find it

**Comment by Evillunte** [comment]
![Screenshot_2023-12-17-20-04-29-19_92460851df6f172a4592fca41cc2d2e6](https://github.com/Rplus/Pokemon-shiny/assets/119182614/febce608-91c7-4469-8592-58e5e2396663)

**Comment by MelkyAir** [comment]
Is already added in PR #294

**Comment by Evillunte** [comment]
Ohh sorry, i closes this one...
I was looking under closed ,but must have miss it

**Comment by Evillunte** [comment]
Hmm.. why cant i see it under closed, just look again....????

![Screenshot_2023-12-17-20-30-17-08_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Rplus/Pokemon-shiny/assets/119182614/71a295e9-3f4e-4353-b6f2-b641f4c17d99)

**Comment by MelkyAir** [comment]
it's under Pull Requests. As no issue was opened.

**Comment by Evillunte** [comment]
Oh never look there. I only look at open and close issue
