### ISSUE TITLE
Miss Shiny: Vanillite family (Dec 25th 2023)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#298]
Release date 25-12-2023

Vanillite
ID#582
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm582.s.icon.png

Vanillish
ID#583
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm583.s.icon.png

Vanilluxe
ID#584
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm584.s.icon.png

**Comment by Evillunte** [comment]
The psyduck family is already out from today (the 18. ) n assignments. 
![Screenshot_2023-12-18-06-34-58-19_a23b203fd3aafc6dcb84e438dda678b6](https://github.com/Rplus/Pokemon-shiny/assets/119182614/b82db213-cd0d-4a8b-ab22-55d6e06b8327)

**Comment by BartmanEH** [comment]
PR #300
