### ISSUE TITLE
Miss Shiny: costume jigglypuff and wigglypuff 

### ISSUE THREAD

**Issue by Evillunte** [Rplus/Pokemon-shiny#301]
Jigglypuff and wigglypuff with ribbon
Release 1 jan. 2024
Image ?

![FB_IMG_1703191777417](https://github.com/Rplus/Pokemon-shiny/assets/119182614/7ad0d108-cf79-4375-b2e7-99ac941fb13f)

**Comment by BartmanEH** [comment]
images not in pokeminer yet

**Comment by BartmanEH** [comment]
so far I've only seen non-256x256 assets in Pokemod Discord server:
![pm39 cJAN_2024 s icon](https://github.com/Rplus/Pokemon-shiny/assets/6135879/9edcbe11-6999-44d8-8559-be94a73e2c54)
![pm40 cJAN_2024 s icon](https://github.com/Rplus/Pokemon-shiny/assets/6135879/fab294b7-3b06-4c07-abaf-7e347bdc4de0)

**Comment by Rplus** [comment]
There is a good service to get different size picuture:
https://wsrv.nl/?&w=256&h=256&we&il&fit=contain&output=webp&url=https://images.plurk.com/6IFqhIk10UtvtCmTW2VRBQ.png

**Comment by BartmanEH** [comment]
...and then upload this ugly upscaled asset into pokeminer? hmmm

**Comment by BartmanEH** [comment]
OK, the real assets are now live thanks to some help I got in Discord. I've created PR #306 to add these

**Comment by Evillunte** [comment]
Not on the list yet .. ( but its on leekdick list and he copy from here 🤔)

**Comment by BartmanEH** [comment]
clearly he doesn't copy from here, it's not even incorporated into the code, let alone deployed to webserver. leekduck copied the source code and must be editing it themself now and using their own webserver. we just need to wait for rplus to accept my Pull Requests and these will be in the list.

**Comment by Evillunte** [comment]
He say he copy from rplus. 🤔

**Comment by Evillunte** [comment]
When you open the list, the jigglypuff is being automatic mark as own...
