### ISSUE TITLE
Miss Shiny: Dusk Form Lycanroc (06-01-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#304]
Lycanroc Dusk
ID#745
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm745.fDUSK.s.icon.png

Released Jan 6th 2024
Source: https://pokemongolive.com/post/lustrous-odyssey-2024?hl=en

**Comment by BartmanEH** [comment]
PR #305

**Comment by MelkyAir** [comment]
Hi @BartmanEH, 

I know this is closed and completed, but might it be an idea to add icons to the Lycanrock?
The colour difference between midday and dusk is for some difficult to see.
Maybe we can add 🌞 to midday, 🌓 to dusk (or 🌞/🌙) and 🌙 to night?

**Comment by BartmanEH** [comment]
I think I can figure out how to do that. I did it before for another mon. I'll take a look.

**Comment by BartmanEH** [comment]
PR #311
