### ISSUE TITLE
Miss Shiny: Hisuian Typhlosion (14-01-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#307]
Hisuian Typhlosion
ID#157
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm157.fHISUIAN.s.icon.png

Release date: Jan 14th 2024
Source: https://pokemongolive.com/post/hisuian-typhlosion-raid-day-event?hl=en

**Comment by BartmanEH** [comment]
PR #308
