### ISSUE TITLE
Miss Shiny: Cutiefly family (13-01-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#309]
Cutiefly
ID#742
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm742.s.icon.png

Ribombee
ID#743
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm743.s.icon.png

Release date: Jan 13th 2024
Source: https://pokemongolive.com/post/dazzling-dream-2024?hl=en

**Comment by BartmanEH** [comment]
PR #310
