### ISSUE TITLE
Miss Shiny: Pikachu’s Indonesia Journey (02-03-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#315]
Pikachu batik shirt
ID#25 
https://github.com/PokeMiners/pogo_assets/blob/0d85111a83767d7e6483ccab672da78bd8e0b84a/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm25.fTSHIRT_03.g2.s.icon.png

Pikachu black balloons
ID#25
https://github.com/PokeMiners/pogo_assets/blob/0d85111a83767d7e6483ccab672da78bd8e0b84a/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm25.fFLYING_04.s.icon.png

Release date: 02-03-2024
Source: https://pokemongolive.com/events/indonesia-journey-bali

**Comment by BartmanEH** [comment]
PR #319
