### ISSUE TITLE
Miss Shiny: Road to Sinnoh - LA Tour (17-02-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#317]
Release date 17-02-'24

Chingling
ID#433
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm433.s.icon.png

Pikachu wearing Rei’s cap
ID#25
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets//pm25.fGOTOUR_2024_B.g2.s.icon.png

Pikachu wearing Lucas’s hat
ID#25
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm25.fGOTOUR_2024_A.g2.s.icon.png

Pikachu wearing Dawn’s hat
ID#25
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm25.fGOTOUR_2024_A_02.g2.s.icon.png

Pikachu wearing Akari’s kerchief
ID#25
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm25.fGOTOUR_2024_B_02.g2.s.icon.png

Hisuian Voltorb
ID#100
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm100.fHISUIAN.s.icon.png

Hisuian Electrode
ID#101
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm101.fHISUIAN.s.icon.png

Hisuian Qwilfish
ID#211
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm211.fHISUIAN.s.icon.png

Overqwil
ID#904
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm904.s.icon.png

Source: https://gotour.pokemongolive.com/event-gameplay?hl=en

**Comment by Evillunte** [comment]
Origin form of palkia and dialga is also in shiny
![Screenshot_2024-01-25-16-16-09-36_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Rplus/Pokemon-shiny/assets/119182614/b928e17c-ca6f-4f76-ba94-0fa5f000f7e3)

**Comment by MelkyAir** [comment]
For Dialga en Palkia PR #314 was already opened and implemented.

**Comment by Evillunte** [comment]
Oh its again because i only look at the close one ..  dont no how to look in the code

**Comment by BartmanEH** [comment]
We can only use pokeminer images. I have no way to point to wraythex(sp?) image repository. We'll have to wait until the assets are in pokeminer GitHub or for RPlus to modify the code to allow other sources.

**Comment by BartmanEH** [comment]
> Oh its again because i only look at the close one ..  dont no how to look in the code

You don't have to look in the code--just check the Open AND Closed Pull Requests (PR). There you will find all the images I've added. Closed should be live in the list. Open are waiting to be incorporated.

**Comment by Evillunte** [comment]
Open/close , is it here (the picture)?
Cant see the new palkia and dialga  in there ? 



![IMG_20240126_135036](https://github.com/Rplus/Pokemon-shiny/assets/119182614/2f5810f0-e6fc-49c6-9e4c-9f3e37132e8a)

**Comment by BartmanEH** [comment]
Those are Issues. You need to check Pull Requests.

**Comment by BartmanEH** [comment]
> We can only use pokeminer images. I have no way to point to wraythex(sp?) image repository. We'll have to wait until the assets are in pokeminer GitHub or for RPlus to modify the code to allow other sources.

OK, it looks like the assets are in pokeminer. example:
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm25.fGOTOUR_2024_A.s.icon.png

**Comment by BartmanEH** [comment]
PR #322 

Note that the current assets for Hisuian Voltorb and Electrode are "outlines" only:
![pm100 fHISUIAN s icon](https://github.com/Rplus/Pokemon-shiny/assets/6135879/a3ce5f7c-fc8b-43ac-ab58-ab5db2d5af22)
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm100.fHISUIAN.s.icon.png?raw=true
![pm101 fHISUIAN s icon](https://github.com/Rplus/Pokemon-shiny/assets/6135879/503e0ee2-a4ae-4136-a794-136fa5173182)
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm101.fHISUIAN.s.icon.png?raw=true

**Comment by MelkyAir** [comment]
Hisuian voltorb family has been updated and outlines have been replaced by real images.
