### ISSUE TITLE
Miss Shiny: Oricorio family (13-02-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#324]
Oricorio Baile
ID#741
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm741.fBAILE.s.icon.png

Oricorio Pau
ID#741
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm741.fPAU.s.icon.png

Oricorio Pompom
ID#741
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm741.fPOMPOM.s.icon.png

Oricorio Sensu
ID#741
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm741.fSENSU.s.icon.png

Release date: 13-02-2024
Source: https://pokemongolive.com/post/carnival-of-love-2024?hl=en

**Comment by BartmanEH** [comment]
PR #326
