### ISSUE TITLE
Miss Shiny: Go Tour - Sinnoh (24-02-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#325]
Shaymin Land 
ID#492
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm492.fLAND.s.icon.png

Shaymin Sky
ID#492
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm492.fSKY.s.icon.png

Stunky family
Stunky
ID#434
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm434.s.icon.png

Skuntank
ID#435
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm435.s.icon.png

Release date: 24-0202024
Source: https://gotour.pokemongolive.com/global?hl=en

**Comment by BartmanEH** [comment]
This is the only hint about Stunky:
<img width="347" alt="Screenshot 2024-02-02 at 9 45 51 AM" src="https://github.com/Rplus/Pokemon-shiny/assets/6135879/abda9cce-81aa-4746-b02e-b6bfb5e7b176">

Where is the evidence about the two forms of Shaymin?

**Comment by BartmanEH** [comment]
PR #327

**Comment by Evillunte** [comment]
Were can i find info on both shaymin release, can only find the one. ( Ticket)

**Comment by BartmanEH** [comment]
> Were can i find info on both shaymin release, can only find the one. ( Ticket)

![image](https://github.com/Rplus/Pokemon-shiny/assets/6135879/5c0311de-0878-4622-90c5-9970e6f034f8)
![image](https://github.com/Rplus/Pokemon-shiny/assets/6135879/90b830bd-88c3-4523-8824-8533f03fc2a5)

**Comment by Evillunte** [comment]
Oh THX. 🩵
It was the change form that get me Wonder. 
I know about the masterwork research,but havent seen the change form.. so that make sense..👍
