### ISSUE TITLE
links to show only Owns/Registered/Released?

### ISSUE THREAD

**Issue by YesThatAllen** [Rplus/Pokemon-shiny#33]
as I work to use this shiny site to track all the things, (see https://github.com/Rplus/Pokemon-shiny/issues/24 ) something that would be useful is the ability to show only the 'mon which are `registered` or ones I `have`

I would imaging the selectors would act like the show selected/unselected  and have url params like you've so kindly added in #19 

Thanks, as always, for your consideration.

**Comment by Rplus** [comment]
There will be a new version site later.
Hope you will like that~

**Comment by Rplus** [comment]
In new version, I use "status" for different view.

If you really need the link that focus on special show case,
Please click the short url button, and share the link directly.

PS:
new version has 4 status: `released`, `registered`, `owne`, `tradable`

![image](https://user-images.githubusercontent.com/1808835/64414440-ecb60f80-d0c5-11e9-95cd-fe3dd9cf0c02.png)

**Comment by YesThatAllen** [comment]
This is a really great feature set. Thank you!
