### ISSUE TITLE
Miss Shiny: Rotom

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#330]
Reward from research
Global Unlock: Ghost in the Machine
Can be obtained by using redeem code: 0HY0UF0UNDM3

Rotom
ID#479
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm479.s.icon.png

Released: 17-02-2024

**Comment by BartmanEH** [comment]
PR #331
