### ISSUE TITLE
Miss Shiny: Basculin (White-striped)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#333]
Basculin
ID#550
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm550.fWHITE_STRIPED.s.icon.png

Released 24-02-2024

**Comment by BartmanEH** [comment]
PR #334

**Comment by BartmanEH** [comment]
merged and deployed. can close this one
