### ISSUE TITLE
Miss Shiny: Pikachu Cap's hat (5-3-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#341]
Pikachu Cap's hat
ID#25
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon/Addressable%20Assets/pm25.fHORIZONS.g2.s.icon.png

Release date: 5 March 2024
Source: https://pokemongolive.com/post/pokemon-horizons-anime-celebration?hl=en

**Comment by BartmanEH** [comment]
PR #342

**Comment by BartmanEH** [comment]
can close this issue
