### ISSUE TITLE
Image export is missing pictograms

### ISSUE THREAD

**Issue by ReneRanzinger** [Rplus/Pokemon-shiny#343]
When exporting the image it misses the pictograms of the pokemon. Example:
![Sammler42-shiny-w1900](https://github.com/Rplus/Pokemon-shiny/assets/2267640/d0587218-1cd1-458e-9dfa-04d5123d411a)

Happens with any selection. Happens on Chrome - both in browser view and the downloaded image. Seems to be working on Firefox though.

**Comment by Rplus** [comment]
This feature(export image) will be removed.
That is because the image size is too big.

I think user can use default browser print function to get the image.

**Comment by ReneRanzinger** [comment]
No need to reopen. But I found this feature very useful when sending people the list what I have and what I am looking for without allowing them access to "my shinies". But I understand the concern regarding the image size.
