### ISSUE TITLE
Wyrdeer is listed as "undefined"

### ISSUE THREAD

**Issue by ReneRanzinger** [Rplus/Pokemon-shiny#344]
![Wyrdeer](https://github.com/Rplus/Pokemon-shiny/assets/2267640/926b693a-46ba-46b9-8b76-ac5e3bf5f542)

**Comment by BartmanEH** [comment]
<img width="432" alt="Screenshot 2024-03-07 at 2 19 47 PM" src="https://github.com/Rplus/Pokemon-shiny/assets/6135879/b4aa82bd-ce37-4ec5-8df6-3a59cb4bf1c9">

It's fine for me. Clear you cache.

**Comment by ReneRanzinger** [comment]
Strange. I cleared the cache, tried "New private window" and even Edge (that I do not usually use). In all cases shows as Undefined. If its just me close the ticket.

**Comment by BartmanEH** [comment]
Let's see if anyone else chimes in. Also the developer may have a suggestion.

**Comment by MelkyAir** [comment]
On leekduck.com or rplus? 
I have undefined on leekduck only.

**Comment by ReneRanzinger** [comment]
leekduck.com 

Will I get banned if I ask what rplus is (beyond the repository owner)?

**Comment by BartmanEH** [comment]
rplus is the repo owner, author (dev) of this tool, web server here: [https://rplus.github.io/Pokemon-shiny/](https://rplus.github.io/Pokemon-shiny/)
leekduck grabs the source and runs their own web server version but I don't think they sync the source code frequently enough so they're running on older version sometimes. it's beyond rplus' control.

**Comment by ReneRanzinger** [comment]
I see that probably mean that this and also #343 is related to leek duck rather than the tool. Feel free to close the tickets than.

**Comment by BartmanEH** [comment]
no, #343 is a real issue. we can wait and see if rplus takes a look at that one. I don't think many people use the image generator feature. also only rplus or the originator can close an issue so you could close this one.
