### ISSUE TITLE
Miss Shiny: flabebe and the evolution]

### ISSUE THREAD

**Issue by Evillunte** [Rplus/Pokemon-shiny#345]
The flower family flabebe in Yellow,Blue,orange,Blue and white 
And the evolution is coming 21 marts 

Sorry again ,cant figure out finding image on my phone🫣 and get them all to here.

![Screenshot_2024-03-16-08-10-13-86](https://github.com/Rplus/Pokemon-shiny/assets/119182614/c15b3dcc-495d-41a8-a507-c2d3289af94d)

**Comment by MelkyAir** [comment]
ID#669
Flabebe Blue
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm669.fBLUE.s.icon.png

Flabebe Orange
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm669.fORANGE.s.icon.png

Flabebe Red
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm669.fRED.s.icon.png

Flabebe White
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm669.fWHITE.s.icon.png

Flabebe Yellow
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm669.fYELLOW.s.icon.png

ID#670
Floette Blue
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm670.fBLUE.s.icon.png

Floette Orange
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm670.fORANGE.s.icon.png

Floette Red
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm670.fRED.s.icon.png

Floette White
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm670.fWHITE.s.icon.png

Floette Yellow
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm670.fYELLOW.s.icon.png

**Comment by Evillunte** [comment]
Can you find florges also🤞
Thx

**Comment by MelkyAir** [comment]
Sorry had to leave before I finished the set. Florges also added.

**Comment by BartmanEH** [comment]
PR #348

**Comment by MelkyAir** [comment]
@Evillunte you can close this request.
