### ISSUE TITLE
missing Cottonee family with Flower Crown

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#349]
assets not in pokeminer yet ([https://github.com/PokeMiners/pogo_assets/issues/89](https://github.com/PokeMiners/pogo_assets/issues/89))

I'm expecting this to be something like:
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm546.cSPRING_2024.s.icon.png
and
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm547.cSPRING_2024.s.icon.png

**Comment by MelkyAir** [comment]
Shiny versions:
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon/Addressable%20Assets/pm546.cSPRING_2024.s.icon.png

https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm547.cSPRING_2024.s.icon.png

**Comment by BartmanEH** [comment]
PR #354
