### ISSUE TITLE
Pumpkaboo family allignment

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#350]
Currently the two pumpkaboo families have tags different from the ingame sizes.
They go from XS, none, XL, XXL in the tool, but ingame they are Small Size, Average Size, Large Size, Super Size.
The usage of XL and XXL is confusing, as Large Size would be just an L, where we now use XL, which is Extra Large aka Super Size.

Could we change these to match the ingame sizes?
e.g. Sm, Av, La, Su
e.g Sm, As, Ls, Ss
e.g. S, M, L, XL

Second, the difference between the costume and the regular is also very difficult to see.
Could we add a top hat emoji to the tag too?
e.g. Sm🎩, Av🎩, La🎩, Su🎩

Last, the tags for pumpkaboo fall outside the borders. Could they be displayed with a "< cr >" or similar so the tag would be under the name?

**Comment by MelkyAir** [comment]
I wasn't aware of this CR.
I don't want both size name and size tag. I suggested to change the tag to match the ingame name.

The confusing part is just why Small Size has tag XS (Xtra Small), Large size has tag XL (Xtra Large), and Super Size has tag XXL (Xtra Xtra Large).Why not stick to the closest size for the tag, S for small, L for Large and XL for Super Size? 
Benefit would also be that the tags will be shorter, so they fit in the borders of the image.  
The situation before CR#166 seems to me better matching the ingame names than after the change.

**Comment by BartmanEH** [comment]
What in game names are you referring to? The initial name the game uses is not immutable--you can change it. I change the names all the time:
![3E5CC50F-AF72-4A85-971D-87F966D57844_4_5005_c](https://github.com/Rplus/Pokemon-shiny/assets/6135879/00a9035e-4d37-435a-bbcf-bdb57f6a849b)

The only thing that is immutable are the size tags:
![553CDC01-1AE5-4BB2-8B83-76E805E887ED_1_201_a](https://github.com/Rplus/Pokemon-shiny/assets/6135879/cd093de1-a5f5-49ab-99f1-140474d83052)

**Comment by MelkyAir** [comment]
I'm referring to the names in the pokedex
![Screenshot_20240318_183218_Pokmon GO](https://github.com/Rplus/Pokemon-shiny/assets/142159643/93e59903-dc79-4460-8948-e76c0bf8b91e)

**Comment by BartmanEH** [comment]
I'm not in agreement to use those names. They are not searchable or identifiable in any way. Only the size tag is searchable and identifiable when viewing the details of a mon.

**Comment by MelkyAir** [comment]
OK, fair enough. Could you then only add the hat emoji to the costumed ones?

**Comment by BartmanEH** [comment]
...or use both size name and size tag on two lines as you suggested which was my original request in #166. Let's see what @Rplus says is possible. In the meantime, I'll append the Hat emoji to costume set but, of course, it won't be visible until we figure out two lines or some other solution.

**Comment by Rplus** [comment]
I think that the identifier char(name_suffix) is not based on their name.
For example: `Charizard(M-X)`, we just use `M` for `MEGA` in simple way.

So, that just helps to identify them.

And then, the next question is:
Could `XS`, `XL`, `XXL` be good to identify different size for Pumpkaboo family.

I think @BartmanEH 's second comment is good:
The size tag is immutable.

For now, the `name_suffix` property is used for different language.
So I think that is not good to use `Sm, Av, La, Su` for name suffix, the user in different language will be confused.

And last, I don't know it is okay or not to add a hat emoji to them.
Them just are different costume style.
Or, should we add hat as suffix for all Pikachu with hat?

**Comment by MelkyAir** [comment]
I think you made a strong case why this is chosen over my suggestion. I will have to live with it.
Would you, @Rplus, be able to comment if we can have a cariage return in the name? For example Pumpkaboo (XXL) is a fraction to wide for the image block. So the last part of (XXL) falls outside the borders. If we would be able to move the tag below the name this would solve that.

In regard to the emoji to the costumed pumpkaboo. We only add emoji's if the image is to difficult to identify the difference.
e.g with the genesect family, or in this case the pumpkaboo and gourgeist with or without a hat. The difference in the image is almost not visible.

**Comment by BartmanEH** [comment]
The first one in the list is the normal one and the one after is the costume one. Seems pretty simple to me.

**Comment by BartmanEH** [comment]
@Rplus I tried injecting style "font-stretch" into the div but it had no effect:
<img width="481" alt="Screenshot 2024-03-20 at 9 40 36 AM" src="https://github.com/Rplus/Pokemon-shiny/assets/6135879/bd976bc1-299a-4dbc-ab7d-b1aa1aad7c2f">
Is there a way I can affect the font of a specific mon?

**Comment by Rplus** [comment]
> @Rplus I tried injecting style "font-stretch" into the div but it had no effect: 
> Is there a way I can affect the font of a specific mon?

`font-stretch` just support some* font-family, not always works.

**Comment by BartmanEH** [comment]
style="transform: scaleX(0.85); transform-origin: 0 0;" works well. How do I add that to just the text part?

**Comment by MelkyAir** [comment]
The alligment now looks great @BartmanEH. Did you want to add the emoji too, or was it voted against it? If so, I'll close this issue.

**Comment by BartmanEH** [comment]
Wanted to do one at a time so it's easy to undo. I'll do a PR to add top hat shortly.

**Comment by BartmanEH** [comment]
PR #353 closes this issue.

**Comment by BartmanEH** [comment]
Under great duress :-) we added a top hat emoji to costume Pumpkaboo family. We iterate that costume pokemon always follow the non-costume version in the list. It should be easy to distinguish them by order in the list. At this time, the author is not prepared to retro-actively name costume pokemon across the board so consider this a one-time exception. Thanks and please close this issue.
