### ISSUE TITLE
Miss Shiny: Sizeable Surprises (04-04-24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#355]
Celesteela
ID#797
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm797.s.icon.png

Kartana
ID#798
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm798.s.icon.png

Wimpod
ID#767
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm767.s.icon.png

Golisopod
ID#768
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm768.s.icon.png

Release date: 4th April 2024
Source: https://pokemongolive.com/post/sizeable-surprises-2024?hl=en

**Comment by MelkyAir** [comment]
I saw Wimpod already added in #352 , but not sure if you added Celesteela and Kartana too at the same time.

**Comment by BartmanEH** [comment]
PR #356
