### ISSUE TITLE
Miss Shiny: Mega Heracross (13-04-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#357]
Mega Heracross
ID#214
EXPECTED LINK: https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm214.fMEGA.s.icon.png
Release date: 13-04-'24
Source: https://twitter.com/PokemonGoApp/status/1771659085357715879/photo/2

**Comment by BartmanEH** [comment]
[https://github.com/PokeMiners/pogo_assets/issues/93#issue-2208753539](https://github.com/PokeMiners/pogo_assets/issues/93#issue-2208753539)

**Comment by MelkyAir** [comment]
image has been added.

**Comment by BartmanEH** [comment]
PR #360
