### ISSUE TITLE
Miss Shiny: from gofest 30may (necrozma,xurkitree,emolga,eevee and Pikachu sun and moon)

### ISSUE THREAD

**Issue by Evillunte** [Rplus/Pokemon-shiny#361]
Release 30 may under go fest sendai and later in NY, madrid, and global

Necrozma (dex number 800)  
Xurkitree (dex 796)
Emolga (587)
Eevee with sun crown
Eevee with moon crown
Pikachu with sun crown
Pikachu with moon crown.

(I Dont know if the new heat room can be shiny)

**Comment by MelkyAir** [comment]
So far confirmed shinies for Sendai. The new images are going to be uploaded in [#pr95](https://github.com/PokeMiners/pogo_assets/pull/95)

30 may Go Fest: Sendai
Pikachu moon crown
ID#25
https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm25.fGOFEST_2024_MTIARA.g2.s.icon.png

Pikachu sun crown
ID#25
https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm25.fGOFEST_2024_STIARA.g2.s.icon.png

Eevee moon crown
ID#133
https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm133.fGOFEST_2024_MTIARA.g2.s.icon.png

Eevee sun crown
ID#133
https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm133.fGOFEST_2024_STIARA.g2.s.icon.png

Emolga
ID#587
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm587.s.icon.png

Unown ?
ID#201
https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm201.fUNOWN_QUESTION_MARK.s.icon.png

Xurkitree
ID#796
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm796.s.icon.png

Necrozma
ID#800
https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm800.s.icon.png

**Comment by Evillunte** [comment]
Thx

**Comment by BartmanEH** [comment]
PR #362
