### ISSUE TITLE
Miss Shiny: Mareanie family (23-05-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#369]
Mareanie 
ID#747
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm747.s.icon.png

Toxapex
ID#748
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm748.s.icon.png

Release Date: 23-05-'24
Source: https://pokemongolive.com/post/ultra-space-wonders-2024?hl=en

**Comment by BartmanEH** [comment]
PR #373

**Comment by MelkyAir** [comment]
@BartmanEH Mareanie family is missing still, but Crabrawler family is already visible which should be only at 16th of June. Can yo7u check if something was mixed up?

**Comment by BartmanEH** [comment]
fixed in PR #376
