### ISSUE TITLE
Trapinch

### ISSUE THREAD

**Issue by Senka222** [Rplus/Pokemon-shiny#37]
hi i dont see trapinch family in that list

**Comment by Senka222** [comment]
same odish

**Comment by Rplus** [comment]
I think you should reload the page.
If you use phone browser and reload doesn't work, you need clear cache at first.
https://support.google.com/accounts/answer/32050

**Comment by YesThatAllen** [comment]
fwiw, I've seen some issues with the page requiring a hard reload. I assumed it was because of the local storage
