### ISSUE TITLE
Miss Shiny: crabrawler, ducklett, jangmo-0

### ISSUE THREAD

**Issue by Evillunte** [Rplus/Pokemon-shiny#374]
Crabrawler and family release madrid gofest 14.jun

Ducklett and family release to New York go fest 5. jul

Jangmo-0 and family will be relasento the globale event 13jul

**Comment by Evillunte** [comment]
![IMG_20240518_201042](https://github.com/Rplus/Pokemon-shiny/assets/119182614/dba1cbcc-452e-417a-991d-9aab8c1b46a7)
![IMG_20240518_201025](https://github.com/Rplus/Pokemon-shiny/assets/119182614/50c66f36-7c56-410e-8590-c3b64b7c157d)
![IMG_20240518_201001](https://github.com/Rplus/Pokemon-shiny/assets/119182614/1a5aa8fe-b851-471a-81c7-7e7877148bbc)

**Comment by MelkyAir** [comment]
14 june Go Fest: Madrid
Crabrawler family
ID#739
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm739.s.icon.png

Crabominab
ID#740
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm740.s.icon.png

Pheromosa
ID#795
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm795.s.icon.png

5 July Go Fest: New York
Ducklett family
ID#580
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm580.s.icon.png

Swanna
ID#581
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm581.s.icon.png

Buzzwole
ID#794
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm794.s.icon.png

13 July Go Fest: Global
Jangmo-o family
ID#782
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm782.s.icon.png

Hakamo-o
ID#783
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm783.s.icon.png

Kommo-o
ID#784
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm784.s.icon.png

Espeon wearing a day scarf
https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm196.fGOFEST_2024_SSCARF.s.icon.png

Umbreon wearing a night scarf
https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm197.fGOFEST_2024_MSCARF.s.icon.png

**Comment by Evillunte** [comment]
Thx  
Espion and umbreon i didnt know was coming

**Comment by MelkyAir** [comment]
@BartmanEH the release date for crabcrawler family seems to be wrong, should be today.
Also umbreon and espeon have been released today and not during the global event, where they were announced.

**Comment by Evillunte** [comment]
Why is it wrong. Crabrawler is on madrid event to this weekend

**Comment by Evillunte** [comment]
Umbreon and espeon was also in sendai event

**Comment by BartmanEH** [comment]
PR #383 fixes Crabrawler family release date

**Comment by BartmanEH** [comment]
PR #384 fixes Umbreon and Espeon w Scarf release date

**Comment by Evillunte** [comment]
Jangmo-0 is already out and has been for 4 days now

**Comment by MelkyAir** [comment]
it will be added in 2 days.. i think we can wait 2 days more and not issue a new PR

**Comment by BartmanEH** [comment]
The original release date was July 13 (you posted it originally). It's such a pain when Niantic changes things and causes all this rework for us! I made PR #391 to address this since I had a little free time.
