### ISSUE TITLE
Miss Shiny: Larvesta family (21-06-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#380]
Larvesta
ID#636
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm636.s.icon.png

Volcarona
ID#637
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm637.s.icon.png

Release date: 21-06-'24
Source: https://pokemongolive.com/post/scorching-steps-2024?hl=en

**Comment by BartmanEH** [comment]
ugh, an egg-locked shiny :-( 

PR #381 adds these.
