### ISSUE TITLE
Miss Shiny: Tynamo family (21-07-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#389]
Tynamo
ID#602
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm602.s.icon.png

Eelektrik
ID#603
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm603.s.icon.png

Eelektross
ID#604
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm604.s.icon.png

Release date: 21-07-'24
Source: https://pokemongolive.com/post/communityday-july-2024-tynamo?hl=en

**Comment by BartmanEH** [comment]
PR #390
