### ISSUE TITLE
Miss Shiny: Popplio family (31-08-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#395]
Popplio
ID#728
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm728.s.icon.png

Brionne
ID#729
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm729.s.icon.png

Primarina
ID#730
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm730.s.icon.png

Release date: 31-08-2024
Source: https://pokemongolive.com/post/communityday-august-2024-popplio?hl=en

**Comment by BartmanEH** [comment]
PR #396
