### ISSUE TITLE
Miss Shiny: Minfoo family & WC24 Pikachu

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#397]
Mienfoo
ID#619
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm619.s.icon.png

Mienshao
ID#620
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm620.s.icon.png

World Championship 2024 Pikachu
ID#025
No image available yet

Release Date: 16-08-2024
Source: https://pokemongolive.com/post/world-championships-event-2024?hl=en

**Comment by BartmanEH** [comment]
Mienfoo family added via PR #398

**Comment by BartmanEH** [comment]
expected image URL:
[https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm25.fWCS_2024.s.icon.png](https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm25.fWCS_2024.s.icon.png)

**Comment by BartmanEH** [comment]
assets added via pull request: [https://github.com/PokeMiners/pogo_assets/pull/102](https://github.com/PokeMiners/pogo_assets/pull/102)

**Comment by BartmanEH** [comment]
my pokeminer PR was merged, asset is live! PR #399 closes this.

**Comment by MelkyAir** [comment]
@BartmanEH Mienshao has the image of mienfoo.

**Comment by BartmanEH** [comment]
fixed w PR #400
