### ISSUE TITLE
Miss Shiny: Skwovet and Wooloo families (03-09-2024)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#401]
Skwovet 
ID#819
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm819.s.icon.png

Greedent
ID#820
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm820.s.icon.png

Wooloo
#831
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm831.s.icon.png

Dubwool
#832
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm832.s.icon.png

release date: 03-09-2024
Source: https://pokemongolive.com/post/go-out-galar-region?hl=en

**Comment by BartmanEH** [comment]
PR #402
