### ISSUE TITLE
Miss Shiny: Passimian (22-09-2024)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#404]
Passimian
ID#766
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm766.s.icon.png

Release date: 22-09-2024
Source: https://pokemongolive.com/post/research-day-oranguru-and-passimian?hl=en

**Comment by BartmanEH** [comment]
Off to Amsterdam for a few days for work. I'll get to this at the latest middle of next week.

**Comment by MelkyAir** [comment]
No worries, welcome in my homecountry! Enjoy it!

**Comment by BartmanEH** [comment]
PR #406

**Comment by BartmanEH** [comment]
@Rplus I don't see this live yet. Was the merge commit deployed to web server?

**Comment by BartmanEH** [comment]
@Rplus ??
