### ISSUE TITLE
Miss Shiny: Zacian (26-09-2024)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#405]
Zacian
ID#888
no image on pokeminers DB, expected link:
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm888.s.icon.png

Release date: 26-09-2024
Source: https://pokemongolive.com/post/legendary-heroes-2024?hl=en

**Comment by MelkyAir** [comment]
@BartmanEH asset is on discord

https://cdn.discordapp.com/attachments/1161600746328969226/1288665531624456274/pm888.fHERO.s.icon.png?ex=66f602cc&is=66f4b14c&hm=7d0d1895d0ce7f7bfdb79fdc8ae20905c036d611af6c88a5924cbaa371d17af3&

**Comment by BartmanEH** [comment]
https://github.com/PokeMiners/pogo_assets/pull/104
I've attempted to upload Zacian and Zamenzenta to pokeminer assets and made a PR

**Comment by BartmanEH** [comment]
PR #413
