### ISSUE TITLE
Miss Shiny: Sewaddle family (05-10-2024)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#408]
Sewaddle
ID#540
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm540.s.icon.png

Swadloon
ID#541
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm541.s.icon.png

Leavanny
ID#542
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm542.s.icon.png

Release date: 05-10-2024
Source: https://pokemongolive.com/post/communityday-october-2024-sewaddle?hl=en

**Comment by BartmanEH** [comment]
PR #407 was already done!

**Comment by MelkyAir** [comment]
Sorry! I just noticed it after I submitted it. Amsterdam has made you even faster ;-)
