### ISSUE TITLE
Consider adding both male and female for hippo where the shiny sprites are fairly different

### ISSUE THREAD

**Issue by bpgross** [Rplus/Pokemon-shiny#41]
I am not looking for male and female across the board - just where they are very different.  Pidove evos are similar, but they have separate dex names, burmy has 3 different colors not all the same gender - I see this as a similar case.

**Comment by BLameLance** [comment]
Can we add this, please? There is unrealized Pokemon like Meowstic and Pyroar, that have different gender forms. This would also be great for the current releases like Hippopotas, Hippowdon, and Unfezant.

**Comment by BLameLance** [comment]
@Rplus so let's get discussing it! :D

**Comment by Rplus** [comment]
I added two family with different gender.
But I am not sure users need that or not.
![image](https://user-images.githubusercontent.com/1808835/154018142-430b4017-b511-4601-a2fa-63d3263ced69.png)

Should we do that for more pokemon like Hippopotas, Hippowdon, and Unfezant?

**Comment by BLameLance** [comment]
I like this feature! I believe people will use it because most shiny hunters are looking for those different gender forms. Please do it for Hippopotas, Hippowdon, and Unfezant. I will use it!!!

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by BartmanEH** [comment]
> Should we do that for more pokemon like Hippopotas, Hippowdon, and Unfezant?
sure, start with the wildly different ones as you identified

**Comment by Rplus** [comment]
I select some pokemon from this diff checking picture.
If there are more pokemon you need, just re-open this issue~
![](https://veekun.com/static/pokedex/downloads/black-white-female-diff.png)
![](https://veekun.com/static/pokedex/downloads/black-white.png)
images soure: https://veekun.com/dex/downloads
