### ISSUE TITLE
Will we add Gigantamax?

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#412]
With the upcoming introduction of Gigantamax pokemon, will we add these too?
A new chapter is added to the dex to register them.

1st one to be released, is most likely the Gigantamax Blastoise.

![pm9 fGIGANTAMAX icon](https://github.com/user-attachments/assets/290baf01-b15f-4457-abf9-cfc48a4e2ad2)

**Comment by BartmanEH** [comment]
maybe. we did add temporary evolutions like Mega and Primal so the pressure is on to add these too. LOL

**Comment by MelkyAir** [comment]
At least there is a max to it. 32 gigantamax forms "only".

**Comment by MelkyAir** [comment]
Closing this issue as future adds will be opened in a separate ticket.
