### ISSUE TITLE
Miss Shiny: Toxel Family (16-11-2024)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#416]
Toxel
ID#848
No image available yet

Toxtricity (Amped Form)
ID#849
No image available yet

Toxtricity (Low Key Form)
ID#849
No image available yet

Release date: 16-11-2024 (Fukuoka), 23-11-2024 (Global)
Source: https://pokemongolive.com/gowildarea/fukuoka?hl=en

**Comment by MelkyAir** [comment]
@BartmanEH low res images on discord.

**Comment by BartmanEH** [comment]
actually the 256x256 ones are there. i'll try to find time to PR them into pokeminer github

**Comment by MelkyAir** [comment]
Did you find them? They are here: https://discord.com/channels/603592836046389259/1161600746328969226/1293306812791001109

**Comment by BartmanEH** [comment]
PR #421
