### ISSUE TITLE
Miss Shiny: Mega Mawile (12-10-2024)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#418]
Mega Mawile
ID#303
https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm303.fMEGA.s.icon.png
Release date: 12-10-'24
[Source: https://twitter.com/PokemonGoApp/status/1771659085357715879/photo/2](https://pokemongolive.com/post/mega-mawile-raid-day-2024?hl=en)

**Comment by BartmanEH** [comment]
PR #419
