### ISSUE TITLE
Miss Shiny: Fukuoka (16-11-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#420]
Pikachu Pop Star 
ID#25
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm25.fPOP_STAR.s.icon.png

Pikachu Rock Star
ID#25
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm25.fROCK_STAR.s.icon.png

Snorlax studded jacket
ID#143
Image not available yet, but non-256 version on discord.

Release date: 16-11-'24
Source: https://pokemongolive.com/gowildarea/gameplay?hl=en

**Comment by BartmanEH** [comment]
PR #422

**Comment by MelkyAir** [comment]
@BartmanEH image of snorlax with jacket seems to be incorrectly displayed.
pm143.fWILDAREA_2024.s.icon
![pm143 fWILDAREA_2024 s icon](https://github.com/user-attachments/assets/f7d3c6e5-6990-47e1-85e7-3ce95df6f530)

**Comment by MelkyAir** [comment]
Both pikas are also not visible yet..

**Comment by BartmanEH** [comment]
> Both pikas are also not visible yet..

PR #435

**Comment by BartmanEH** [comment]
> pm143.fWILDAREA_2024.s.icon

PR #436
