### ISSUE TITLE
Miss Shiny: Saree Pikachu (1-11-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#423]
Saree Pikachu
ID#25
Image on discord, wrong filename: PM25FD2.PNG
![PM25FD2](https://github.com/user-attachments/assets/596b1d18-b723-4995-aa01-21ad1b8910c1)

Release date: 1-11-'24
Source: https://pokemongolive.com/post/festival-of-lights-2024?hl=en

**Comment by BartmanEH** [comment]
actually in pokeminer Discord the filename is pm25.fDIWALI_2024.s.icon_1.png as shown here:
[https://discord.com/channels/612598598768656384/685681041624924180/1298753267756433550](https://discord.com/channels/612598598768656384/685681041624924180/1298753267756433550)
I'm a little worried about the non-standard "icon_1" part.

**Comment by MelkyAir** [comment]
Maybe its icon_1 as there is a 2nd pika with the same name, but the male version and a different costume.

**Comment by BartmanEH** [comment]
Is that other pika image in pokeminer discord?

I find it a mess to find things there. Posts aren't labelled etc. so searching for 'pikachu' doesn't find the post with pika images. The post is just something like "new assets". Argh.
