### ISSUE TITLE
Miss Shiny: Gigantamax 

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#424]
Gigantamax Venusaur
ID#003
image on discord : pm3.fGIGANTAMAX.s.icon.png
![pm3 fGIGANTAMAX s icon](https://github.com/user-attachments/assets/108c0096-a474-4b5b-8649-214402d815f9)

Gigantamax Charizard
ID#006
image on discord : pm6.fGIGANTAMAX.s.icon.png
![pm6 fGIGANTAMAX s icon](https://github.com/user-attachments/assets/04d8fba0-1d5e-4381-b206-2f7e3e85581d)

Gigantamax Blastoise
ID#009
image on discord : pm9.fGIGANTAMAX.s.icon.png
![pm9 fGIGANTAMAX s icon](https://github.com/user-attachments/assets/1613b5d6-2c4e-4f33-99e0-f6a7734f1c40)

Release date: 26-10-'24
Source: https://pokemongolive.com/post/go-bigger-gigantamax?hl=en

Gigantamax Gengar
ID#094
image on discord, wrong name, should be: pm94.fGIGANTAMAX.s.icon.png
![pm94 fGIGANTAMAX s icon](https://github.com/user-attachments/assets/c7ac0042-7506-46f4-a3bb-4226484ab9f0)

Release date: 31-10-'24
Source: https://pokemongolive.com/post/halloween-part-2-2024?hl=en

Gigantamax Toxtricity
ID#849
image on discord : pm849.fGIGANTAMAX.s.icon.png
![pm849 fGIGANTAMAX s icon](https://github.com/user-attachments/assets/38ce0386-8448-48dc-913d-d35c9d5abe6f)

Release date: 16-11-'24
Source: https://pokemongolive.com/gowildarea/gameplay?hl=en

**Comment by MelkyAir** [comment]
Added Giga Gengar

**Comment by MelkyAir** [comment]
@BartmanEH can you assist in a PR to get the images (these and the other open I's) added? Or tell me how to add them at pokemod? How do you see the image is the correct 256x256 format and even more important, how do you determine the file name? Questions, questions.. so much questions!

**Comment by BartmanEH** [comment]
Ugh, I don't have time to keep up with all this. It's a lot of work to find images in Discord, check sizes, make a pokeminer repo clone, add them in the right spot, make a pull request to get them into pokeminer, then wait for PR to be accepted, then make a repo clone of shiny checklist, add the references there, PR again... it's a lot of work! As for training someone else, that's even more work lol. I'm self-taught. I made some errors that the repo authors were kind of enough to help me through. But you don't even know how to check an image file's dimensions? The filenames are mined straight from the game assets.

**Comment by MelkyAir** [comment]
I feel you, it's a lot of work for a hobby... is there anything in this process I can help you with?
I can see the dimensions of the images, and there I can see for some they are 256x256, just wasn't sure if this is the correct format you (we) need.
Would it help if I add the 256x256 images in the open issue? Or the discord link to the image?
In regards to the name, some have the default name format (pmxx...icon.s etc), but for instead the Sari Pikachu on discord is named PM25FD2.PNG. Would a name like that be accepted too?

**Comment by BartmanEH** [comment]
Yes it would help if you pulled the assets and posted them in the associated issue thread, or a new one. 

the filename PM25FD2.PNG does not look correct--maybe this was a preliminary asset push? As far as I know, every asset ultimately ends up in the format pmxx...icon.s.png.

start here:
[https://github.com/PokeMiners/pogo_assets/find/master/](https://github.com/PokeMiners/pogo_assets/find/master/)
put in the search bar: "Images/Pokemon - 256x256/Addressable Assets/pm25." and I think you'll find every Pika released starts with "pm25."
<img width="626" alt="Screenshot 2024-10-29 at 3 25 51 PM" src="https://github.com/user-attachments/assets/5b37a0b7-bdc8-423f-be16-a549180629b7">

I doubt the pokeminer people would accept a PR to use random/temporary asset names.

**Comment by MelkyAir** [comment]
Ah ok, that is what I thought.. for some we will have to wait then.
I'll add the images to the correct threads.

**Comment by MelkyAir** [comment]
@BartmanEH I have added the gigantamax images. Let me know if this is helpfull.
The Halloween release images are named incorrectly, and no educated guess can be made, so I'm researching that further.
