### ISSUE TITLE
Miss Shiny: Halloween '24

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#425]
Froakie wearing a Pokémon Halloween costume
ID#656
image on discord wrong name, should be: pm656.cFALL_2024.s.icon.png
![pm656 cFALL_2024 s icon](https://github.com/user-attachments/assets/c5392152-110b-495f-bbf7-d0c4a1e6520d)

Frogadier wearing a Pokémon Halloween costume
ID#657
image on discord wrong name, should be: pm657.cFALL_2024.s.icon.png
![pm657 cFALL_2024 s icon](https://github.com/user-attachments/assets/52007eff-4074-48bc-83a6-31e6f4a29808)

Greninja wearing a Pokémon Halloween costume
ID#658
image on discord: pm658.cFALL_2024.s.icon.png
![pm658 cFALL_2024 s icon](https://github.com/user-attachments/assets/bc6a4329-0be0-492b-851d-0f2fb4d313f1)

Rowlet wearing a Pokémon Halloween costume
ID#722
image on discord:

Dartrix wearing a Pokémon Halloween costume
ID#723
image on discord:

Decidueye  wearing a Pokémon Halloween costume
ID#724
image on discord:

Release date: 22-11-'24
Source: https://pokemongolive.com/post/halloween-part-1-2024?hl=en

**Comment by BartmanEH** [comment]
Froakie family PR [https://github.com/PokeMiners/pogo_assets/pull/109](https://github.com/PokeMiners/pogo_assets/pull/109)

**Comment by MelkyAir** [comment]
Unfortunately I see no way to upload the file here with the correct name...I'm also not allowed to upload them directly to PokeMiners using Add File option. Sorry I can't be more helpful here.

**Comment by MelkyAir** [comment]
Could we safely assume the filename for the Rowlet should be pm722.cFALL_2024.s.icon.png, pm723.cFALL_2024.s.icon.png and pm724.cFALL_2024.s.icon.png?

**Comment by BartmanEH** [comment]
Let's assume. Worst case I'll do another PR down the road to change the asset names

**Comment by MelkyAir** [comment]
pm722.cFALL_2024.s.icon
![pm722 cFALL_2024 s icon](https://github.com/user-attachments/assets/8f244428-1398-4bc6-93ef-cff2b70513e1)

pm723.cFALL_2024.s.icon
![pm723 cFALL_2024 s icon](https://github.com/user-attachments/assets/95a2e398-f97a-4bfa-889a-e077cab70711)

pm724.cFALL_2024.s.icon
![pm724 cFALL_2024 s icon](https://github.com/user-attachments/assets/12b1a4a6-d3cb-4115-a171-03c19561a347)

**Comment by BartmanEH** [comment]
pokeminer PR [https://github.com/PokeMiners/pogo_assets/pull/110](https://github.com/PokeMiners/pogo_assets/pull/110)

**Comment by BartmanEH** [comment]
PR #431

**Comment by svivian** [comment]
Why are only the shinies added? The non-shiny images are not there for the Froakie/Rowlet lines as well as the Gigantamax forms.
