### ISSUE TITLE
Miss Shiny: Smoliv family (7-11-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#427]
Smoliv
ID#928
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm928.s.icon.png

Dolliv
ID#929
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm929.s.icon.png

Arboliva
ID#930
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm930.s.icon.png

Release date: 7-11-'24
Source: https://pokemongolive.com/post/harvest-festival-2024?hl=en

**Comment by BartmanEH** [comment]
PR #428
