### ISSUE TITLE
Miss Shiny: Max Out Finale event (27-11-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#437]
Regieleki
ID#894
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm894.s.icon.png

Regidrago
ID#895
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm895.s.icon.png

Galarian Corsola
ID#222 
pm222.fGALARIAN.s.icon
![pm222 fGALARIAN s icon](https://github.com/user-attachments/assets/d655ffd4-f10c-42d9-8772-f179e5617104)

Cursola
ID#864
pm864.s.icon
![pm864 s icon](https://github.com/user-attachments/assets/6d49018b-3d95-4d80-910b-2267973aac50)

Release date:: 27-11-'24
Source: https://pokemongolive.com/post/max-out-finale-2024?hl=en

**Comment by BartmanEH** [comment]
PR #438 adds Regieleki & Regidrago

**Comment by BartmanEH** [comment]
[PR](https://github.com/PokeMiners/pogo_assets/pull/117) adds G Corsola and Cursola to Pokeminers

**Comment by MelkyAir** [comment]
@BartmanEH For some reason the G Corsola is marked registered automatically. Any ideas how that happened?

**Comment by BartmanEH** [comment]
I will investigate

**Comment by BartmanEH** [comment]
hopefully PR #441 fixes this. I'm not really sure how the "Type" thing works.
