### ISSUE TITLE
Miss Shiny: Gigantamax Lapras (8-12-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#440]
Gigantamax Lapras
ID#0131
pm131.fGIGANTAMAX.s.icon.png

https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm131.fGIGANTAMAX.s.icon.png?raw=true

Release date: 8-12-'24
Source: https://pokemongolive.com/post/gigantamax-lapras-max-battle-day?hl=en

**Comment by BartmanEH** [comment]
PR #444
