### ISSUE TITLE
Miss Shiny: Genesect Chill Drive (3-12-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#442]
Genesect ❄️
ID#649
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm649.fCHILL.s.icon.png

Release date: 3-12-'24
Source: https://pokemongolive.com/post/just-my-cup-of-tea-2024?hl=en

**Comment by BartmanEH** [comment]
PR #443
