### ISSUE TITLE
Miss Shiny: Basculin Blue en Red striped

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#445]
Looks like we had en stealth shiny release..

Basculin Red Striped
#550
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm550.fRED_STRIPED.s.icon.png

Basculin Blue Striped
#550
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm550.fBLUE_STRIPED.s.icon.png

Release date: December 3rd
Source: 
![2ca0525b-c453-42db-858e-341fa61cc65b](https://github.com/user-attachments/assets/d948314b-e928-4808-bab7-565150e78ce0)
Also found on non official overview:
![WhatsApp Image 2024-11-26 at 18 12 24](https://github.com/user-attachments/assets/eac2b0ad-ccc7-4e23-b9da-3b58b28745eb)

**Comment by BartmanEH** [comment]
hatch or matteo gift only.... let's sit on this a bit and get more confirmation

**Comment by BartmanEH** [comment]
@MelkyAir seen anymore confirmation from Niantic that this is officially released? I think it's egg only. Also where's your post about missing 4 costume Pika from the City events? :-)

**Comment by MelkyAir** [comment]
I got the basculin myself from an egg... blue striped. From what I have heard so far, indeed 7km eggs only. 

The city events are February!! I tried to not overload you with requests ;-) So in Jan I'll add them, or as soon as the sprites of the pikas become available.

**Comment by BartmanEH** [comment]
PR #447

**Comment by MelkyAir** [comment]
@Rplus and @BartmanEH the last PR's don't show up live.. as far as I can see the data is correct. Any idea's?

**Comment by Rplus** [comment]
Sorry~ here I come~
