### ISSUE TITLE
Miss Shiny: Holiday part 1 (17-12'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#446]
Sandygast
ID#769
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm769.s.icon.png

Palossand
ID#770
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm770.s.icon.png

Dedenne wearing holiday attire
ID#702
![PM702C1](https://github.com/user-attachments/assets/390e0992-5d10-473f-b1d4-139601d9831a)
Image name incorrect on Discord.
My guess would be: pm702.cHOLIDAY.s.icon.png

Release date: 17-12-'24
Source: https://pokemongolive.com/post/holiday-part1-2024?hl=en

**Comment by MelkyAir** [comment]
Correct name is pm702.cHOLIDAY.s.icon.png.
https://github.com/PokeMiners/pogo_assets/blob/master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm702.cWINTER_2024.s.icon.png

**Comment by BartmanEH** [comment]
PR #451
