### ISSUE TITLE
Miss Shiny: Holiday part 2 (22-12'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#449]
Wooloo wearing holiday attire
ID#831
![PM831C1](https://github.com/user-attachments/assets/a559da9b-ba49-4e0f-b425-72a8814d7afc)
Name on discord incorrect, guess: pm831.cHOLIDAY.s.icon.png

Dubwool wearing holiday attire
ID#832
![PM832C2](https://github.com/user-attachments/assets/69c07a65-d6ce-4610-899e-ae8139b6b744)
Name on discord incorrect, guess: pm832.cHOLIDAY.s.icon.png

Cetoddle
#974
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm974.s.icon.png

Cetitan
#975
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm975.s.icon.png

**Comment by MelkyAir** [comment]
Correct names are: 
pm831.cWINTER_2024.s.icon.png and pm832.cWINTER_2024.s.icon.png

https://raw.githubusercontent.com/PokeMiners/pogo_assets/0dc35f219912d0938fc7900d9223aee32055ea5c/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm831.cWINTER_2024.s.icon.png

https://raw.githubusercontent.com/PokeMiners/pogo_assets/0dc35f219912d0938fc7900d9223aee32055ea5c/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm832.cWINTER_2024.s.icon.png

**Comment by BartmanEH** [comment]
PR #450

**Comment by MelkyAir** [comment]
@BartmanEH the costumed wooloo fam is marked registered again.

**Comment by BartmanEH** [comment]
trying with PR #455 to fix this by adding "isotope"
