### ISSUE TITLE
Shiny date list?

### ISSUE THREAD

**Issue by guitaristtom** [Rplus/Pokemon-shiny#45]
Is there anything I can do to help with getting the shiny release date list up to date in your [pms.json](https://github.com/Rplus/Pokemon-shiny/blob/master/assets/pms.json) file?

**Comment by Rplus** [comment]
That will be a great idea, 
you can create a PR on this repo, or just write on here.

You can check the released date by https://www.p337.info/pokemongo/pages/shiny-release-dates/

**Comment by Rplus** [comment]
The syntax of released date is just like 
https://github.com/Rplus/Pokemon-shiny/blob/master/assets/pms.json#L846
```
  {
    "dex": 25,
    "name": {
      "de": "Pikachu",
      "en": "Pikachu",
      "fr": "Pikachu",
      "ja": "ピカチュウ",
      "kr": "피카츄",
      "zh": "皮卡丘"
    },
    "shiny_released": false,
    "released_date": "2020/05/08",
    "isotope": "_23",
    "family": "Pikachu_23"
  },
```

**Comment by guitaristtom** [comment]
I understand, but I noticed that several Pokemon in the file have their `shiny_released` value as true, but there isn't a date there for it. Is there any way I can contribute the list of dates and if that would be helpful at all for you?

**Comment by Rplus** [comment]
You could just add `released_date` for that.

Just like:

```diff
  {
    "dex": 25,
    "name": {
      "de": "Pikachu",
      "en": "Pikachu",
      "fr": "Pikachu",
      "ja": "ピカチュウ",
      "kr": "피카츄",
      "zh": "皮卡丘"
    },
    "shiny_released": true,
+   "released_date": "2020/05/08",
    "isotope": "_23",
    "family": "Pikachu_23"
  },
```

**Comment by Rplus** [comment]
Another question is:
Is it a good idea for showing released date?
and where it should be?

**Comment by NickWedzinga** [comment]
Is there a reason behind why the few Pokémon that have released_date set also have shiny_released set as false?

**Comment by Rplus** [comment]
The `released_date` will overwrite `shiny_released`.
So, it could auto switch from `false` to `true` when `released_date` comes. (schedule feature)

**Comment by rekire** [comment]
I wrote today a small parser and patched the data. I hope that the changes are fine.

I noticed that some dates do not match. I didn't verify if the data of that linked page are correct.
