### ISSUE TITLE
Miss Shiny: Sprigatito family (05-01-'25)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#453]
Sprigatito
ID#906
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm906.s.icon.png

Floragato
ID#907
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm907.s.icon.png

Meowscarada
ID#908
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm908.s.icon.png

Release date: 05-01-'25
Source: https://pokemongolive.com/post/communityday-january-2025-sprigatito?hl=en

**Comment by BartmanEH** [comment]
PR #454

**Comment by BartmanEH** [comment]
hey @MelkyAir ... in future, I don't need to whole link to the image file--I just need you to confirm that the image is available and that it's the standard image name or what the special image name is. So here I just need to know something like "standard pmXXX image file name available". Just trying to save you some work!
