### ISSUE TITLE
Can't see pokemon images

### ISSUE THREAD

**Issue by Sylaryen** [Rplus/Pokemon-shiny#50]
Hi!
I can't use the checklist because pokemon images don't load. I used Chrome, Firefox, Safari, Edge, different networks – the problem remains. What should I do?
<img width="1280" alt="Снимок экрана 2020-09-09 в 01 25 51" src="https://user-images.githubusercontent.com/70115918/92534332-266fa800-f23d-11ea-925c-c30961ffbbf8.png">

**Comment by Rplus** [comment]
I'm not sure what is wrong with your browser,
but it wroks fine on my computer for browsing LeekDuck website.

Or you could try to go to my site.
https://rplus.github.io/Pokemon-shiny/

If you have problem to browse website, you could try to open devtool by pressing "F12" key to see what is going wrong.
The "Console" tab in DevTool will print some Error infomation.
