### ISSUE TITLE
shiny Spinda #2

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#51]
shiny Spinda #2 has been out for almost 2 weeks ;-)

**Comment by Rplus** [comment]
Here it is
![image](https://user-images.githubusercontent.com/1808835/92955554-f07a3000-f497-11ea-9e0f-4dd99bc00122.png)

And it is a PR #48

If you don'y see it, try to reload your browser again.

**Comment by BartmanEH** [comment]
Sorry I have no idea what a pull request (PR) is so I only checked for open issues. In addition to Spinda #2, what two others have you enabled that LeekDuck has not? they have 509 and you have 512

**Comment by Rplus** [comment]
Well, I'm not sure.
But maybe you could see the `pms.josn` history to try to find the newer items.
https://github.com/Rplus/Pokemon-shiny/commits/master/assets/pms.json

**Comment by Rplus** [comment]
I see that, Ledyba and Ledian. :P

**Comment by BartmanEH** [comment]
Your 'Times New Roman' pokemon name font is too ugly, @Rplus. Otherwise I'd use your list :-)

**Comment by Rplus** [comment]
Well, I'm not sure which font family is better on Windows.
Do you have any idea?

**Comment by BartmanEH** [comment]
[Websafe fonts](https://websitesetup.org/web-safe-fonts-html-css/)
Arial is nice and clean. I'm more partial to Verdana.

**Comment by Rplus** [comment]
Could you take a screenshot of the font rendering?
I'm not sure where you need the better font. :D

**Comment by BartmanEH** [comment]
Sorry, I didn't mean to make a big deal of this:
![image](https://user-images.githubusercontent.com/6135879/93923287-28c40e80-fce1-11ea-95c0-440abb31dcaf.png)

**Comment by Rplus** [comment]
Ok done, refresh later~ (~5 mins)

**Comment by BartmanEH** [comment]
[Nice one, bruva! I said... nice bruv!](https://www.youtube.com/watch?v=Heqi1XKg4wc)

Now consider my [enhancement request](https://github.com/Rplus/Pokemon-shiny/issues/52) :-)
