### ISSUE TITLE
Italian names not shown + ideas

### ISSUE THREAD

**Issue by DaRkViVi** [Rplus/Pokemon-shiny#61]
Pokémon names are not shown in italian, just an "Undefined". They are the same as the English/Spanish ones, so it should be easy to fix.

I would like to ask the following too:

- Add Mega Evolutions
- Add a Search bar
- Add Upcoming shinies (Pokémon that are already announced but not yet released), maybe with a filter to block them from being selected until the release date

**Comment by Rplus** [comment]
1.
add Mega Evolutions is okay, I'll try to add those images.

2.
What did you want? Search bar or filter bar?
I think if you just want to find something, use native search in browser will be better.

3.
Upcoming shiny pokemon, I don't think it is necessary.
Someone has requested a feature about sort by release date ( #45 ),
I think that might be what you need (but just add somehing upcoming)? 
But there is a question: How the UI should be?

**Comment by DaRkViVi** [comment]
2. I mean a search bar on top where you write, for example, charmander and it will show just the entries of this Pokémon (standard and costumes)
3. Maybe you set a standard background color for them and disable the click like when you click the lock button (but only for them).
