### ISSUE TITLE
Shiny Sprites missing

### ISSUE THREAD

**Issue by WbaLbaDubDub** [Rplus/Pokemon-shiny#64]

**Comment by Rplus** [comment]
?

**Comment by WbaLbaDubDub** [comment]
The whole list looks like this. I reset all my lists, deleted everything I had saved, and this is still what I see. 
![shiny list example](https://user-images.githubusercontent.com/74367029/99087493-d2fd3b80-2598-11eb-8abe-42296dca6083.jpg)

**Comment by Rplus** [comment]
Try to hard reload the page by `ctrl + shift + R`.
Or use my site https://rplus.github.io/Pokemon-shiny/

**Comment by WbaLbaDubDub** [comment]
Thanks, unfortunately neither thing worked. Ctrl+Shit+R didn't change anything, and your site looks the same. Could it be an issue with a browser extension? I'm using Chrome.

**Comment by Rplus** [comment]
`ctrl + shift + i` to open the devtool, and reload the page.
I need error message in devtool to understand what is wrong with that. : )

**Comment by WbaLbaDubDub** [comment]
Now it's working again, I can see all the sprites. I have no idea why, but I'll close this issue until it happens again.
