### ISSUE TITLE
Explorer Pikachu and Rufflet/Braviary

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#66]
Just curious why Cubchoo/Beartic got added before Explorer Pikachu and Rufflet/Braviary which were released earlier.

**Comment by Rplus** [comment]
update Explorer pikachu 4d29e37c33df8f777ed26a3dc2a34be40781ab04
fix Rufflet release date efd415545297e1dcaf964e158472838694a27a51
