### ISSUE TITLE
Cubchoo and Delibird Event Error

### ISSUE THREAD

**Issue by BLameLance** [Rplus/Pokemon-shiny#69]
I recently got the Cubchoo and Delibird shiny, but every time I save, when I refresh the page, both the normal Cubchoo and Delibird plus their event counterpart (which I did not catch during the event) are selected.. I just wanted you to be aware of this error. It did it when I created a new shiny list also.

**Comment by Rplus** [comment]
That issue might be solved on https://github.com/Rplus/Pokemon-shiny/commit/1b800ceeed1802ad0c4a32b0396371c052749dbb
Could you check the update time is newest?

**Comment by BLameLance** [comment]
The last time the list was updated was on January 03, 2021 (I am using the Leekduck list)

**Comment by Rplus** [comment]
You might need to wait for Leekduck updating, or use mine https://rplus.github.io/Pokemon-shiny/
