### ISSUE TITLE
“Get Short URL” is broken

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#72]
Something weird is happening in Safari for me. I manually made a tiny URL:
https://tinyurl.com/4k9537xn
This redirects to:
https://rplus.github.io/Pokemon-shiny/
But with the correct custom shiny list.
And when I hit the “Get short URL” button, all I see is:
Share shiny list 
See /corsdemo for more info

**Comment by Rplus** [comment]
relative with https://github.com/Rob--W/cors-anywhere/issues/301

for now, you might click `Request temporary access to the demo server` at https://cors-anywhere.herokuapp.com/corsdemo

**Comment by BartmanEH** [comment]
What’s the long term solution?

Also, why does pasting this:
`https://rplus.github.io/Pokemon-shiny/?nickname=living+shiny+dex&show=all&lang=en&dex=172_01-25_01-173&own=1-2-3-3_51-1_f19-1_11-1_14-4-5-6-6_51-6_52-4_f19-4_11-4_14-7-8-9-9_51-7_05-8_05-9_05-7_f19-7_11-7_14-10-11-12-13-14-15-15_51-16-17-18-18_51-19-20-20_11-19_61-20_61-23-24-172-25-26-172_02-25_02-26_02-25_03-26_03-25_04-26_04-26_01-25_05-26_05-25_07-26_07-25_08-26_08-25_f19-25_11-25_12-25_22-25_23-25_24-25_25-25_4thY-25_27-26_27-25_m2020-25_winter2020-25_28-26_28-26_61-27-28-27_61-28_61-29-30-31-32-33-34-33_11-35-36-37-38-37_61-38_61-174-39-40-41-42-169-43-44-45-182-48-49-50-51-50_61-51_61-52-53-52_61-53_61-54-55-56-57-58-59-60-61-62-186-63-64-65-66-67-68-69-70-71-72-73-74-75-76-74_61-75_61-76_61-77-78-79-80-199-79_2020-80_2021-81-82-462-83-84-85-86-87-88-89-88_61-89_61-90-91-92-93-94-94_51-94_11-94_26-95-208-96-97-98-99-100-101-102-103-103_61-104-105-105_61-108-463-109-110-111-112-464-113-242-114-465-115-116-117-230-118-119-120-121-122-123-212-238-238_16-124-239-125-466-240-126-467-127-128-129-130-131-133-134-135-136-196-197-470-471-133_07-134_07-135_07-136_07-196_07-197_07-470_07-471_07-133_11-137-233-474-138-139-140-141-142-144-145-146-147-148-149-150-152-153-154-155-156-157-158-159-160-161-162-165-166-170-171-175-175_12-176-468-177-178-179-180-181-181_51-298-183-184-438-185-190-424-191-192-193-469-194-195-198-430-200-429-201_11-201_17-201_22-201_25-201_28-201_30-201_31-360-202-202_11-204-205-206-207-472-209-210-211-213-215-461-216-217-220-221-473-225-225_winter2020-227-228-229-229_51-234-234_08-241-243-244-245-246-247-248-249-250-251-252-253-254-255-256-257-258-259-260-261-262-263-264-265-266-267-268-269-270-271-272-273-274-275-276-277-278-279-280-281-282-475-287-288-289-290-291-296-297-300-301-302-302_f20-303-304-305-306-307-308-309-310-311-312-313-314-406-315-407-318-319-320-321-325-326-327_11-327_12-327_13-327_14-327_15-327_16-327_17-327_18-328-329-330-333-334-335-336-337-338-339-340-343-344-345-346-347-348-349-350-351-353-354-355-356-477-359-361-362-478-366-367-368-370-371-372-373-374-375-376-377-378-379-380-381-382-383-384-386_11-387-388-389-390-391-392-393-394-395-401-402-403-403_16-404-405-412_11-412_12-412_13-413_11-413_12-413_13-414-418-419-425-426-427-427_12-428-431-432-436-437-442-443-444-445-447-448-449-450-451-452-453-453_16-454-459-460-460_51-485-487_12-487_11-488-491-495-496-497-504-505-506-507-508-519-520-521-524-525-526-527-528-532-533-534-557-558-562-563-572-573-597-598-599-600-601-613-613_winter2020-614-631-632-633-634-635-638-639-640-649_11-808-809`
End up getting truncated to just:
`https://rplus.github.io/Pokemon-shiny/ `
I can’t keep copies of the full URL anymore.

**Comment by Rplus** [comment]
In fact, before you click the button `Get Short URL`, the link `Share shiny list` is full url already.
![image](https://user-images.githubusercontent.com/1808835/107886450-e07ce580-6f3a-11eb-9d9a-cd912aeb7105.png)

Click the button, it will replace the link with shorten url.
The problem you found is just the middleware cors-anywhere has some issues now,
I have updated that with Google apps script to generate tinyurl.

**Comment by BartmanEH** [comment]
We are back in business. thanks

**Comment by BartmanEH** [comment]
I dunno, I don’t understand this CORS business. I’m still getting the CORS error, so I requested temp access again but now the Get short URL button does nothing at all.

**Comment by Rplus** [comment]
Could you take a screenshot with the error status?

**Comment by BartmanEH** [comment]
When I tap the Get short URL button, nothing happens. If I keep tapping it, after about 4/5 clicks, a blank dialog box pops up with a close button:
![IMG_0126](https://user-images.githubusercontent.com/6135879/107975747-93266580-6f86-11eb-83e3-4d1b035da70e.jpeg)

The CORS error has gone away. I think I didn’t wait long enough after requesting demo access. This is gonna be a pain to do every day—have to save a different bookmark to the request access page.

**Comment by BartmanEH** [comment]
![IMG_0127](https://user-images.githubusercontent.com/6135879/108007569-4e252200-6fcc-11eb-8a0e-7825f91ea611.png)

**Comment by Ondrashek** [comment]
Share shiny list get this url: https://leekduck.com/shiny/See%20/corsdemo%20for%20more%20info

**Comment by Rplus** [comment]
@Ondrashek 
Thanks for giving feedback.

For now, (it is just a workaround), you might click Request temporary access to the demo server at https://cors-anywhere.herokuapp.com/corsdemo
And then, you could go back to shiny list to generate short url again.
