### ISSUE TITLE
can we set custom colors? 

### ISSUE THREAD

**Issue by YesThatAllen** [Rplus/Pokemon-shiny#74]
it's very hard for me to distinguish between:

State | Color
-- | --
tradeable | hsla(60, 80%, 35%, 1)
owned | hsl(60, 90%, 45%)

is there a way we can set custom colors?

 in my mind it would be like:

  - tradable: green
  - registered: yellow
  - unregistered: red
 - unowned : grey

**Comment by Rplus** [comment]
Okay, that will be more friendly~

**Comment by YesThatAllen** [comment]
Awesome. 

I set the first color to be grey (unavailable for trading) and the second to be red (friends might see it to ask for it)

Thanks!
