### ISSUE TITLE
Costume shinies auto selected despite manually unselecting

### ISSUE THREAD

**Issue by moraug** [Rplus/Pokemon-shiny#75]
https://tinyurl.com/ycnh5xwr
Here's an example. Following this link you will see my "326" shinies, despite me only selecting 322, saving it that way and later loading that url the service provided. The 4 extras are ribbon cubchoo, ribbon delibird, 2020 slowpoke and 2021 slowbro. I have regular versions of each, but none of that costumed ones. I tried deselecting them and saving again - once I reload they are selected once again.

**Comment by Rplus** [comment]
It is dupulated with #69
