### ISSUE TITLE
Shiny check on leekduck fail

### ISSUE THREAD

**Issue by l3arc3ax** [Rplus/Pokemon-shiny#78]
Now, when I check one shiny on the leek duck page, shiny color cange to non shiny colors
![Screenshot_20210301-125828_Chrome](https://user-images.githubusercontent.com/79866643/109538349-f7205200-7a8d-11eb-9264-67b70843daa6.jpg)

Thanks
Luus E

**Comment by Rplus** [comment]
Hey, this is a feature, not a bug.
You could see the original color when your mouse cursor move in.

If you don't need this feature, just disable `compare images` in control panel.
![image](https://user-images.githubusercontent.com/1808835/109659517-b7975a00-7ba2-11eb-90f3-7e7bd00a6b4c.png)

**Comment by l3arc3ax** [comment]
Thats ok, Thanks for supportLuis ESent from my Smartphone.
-------- Original message --------From: Rplus <notifications@github.com> Date: 3/2/21  9:02 AM  (GMT-05:00) To: Rplus/Pokemon-shiny <Pokemon-shiny@noreply.github.com> Cc: l3arc3ax <learcex@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Rplus/Pokemon-shiny] Shiny check on leekduck fail (#78) 
Hey, this is a feature, not a bug.
You could see the original color when your mouse cursor move in.
If you don't need this feature, just disable compare images in control panel.
