### ISSUE TITLE
URL-Shortener doesn't work

### ISSUE THREAD

**Issue by katipierson** [Rplus/Pokemon-shiny#81]
i click on "Kurze URL erhalten" and i get a error since a few weeks.

Have a look on the screenshot;
![grafik](https://user-images.githubusercontent.com/5971275/111027175-d1c90780-83ee-11eb-8868-1686b5ddd9e3.png)

**Comment by Rplus** [comment]
use my site https://rplus.github.io/Pokemon-shiny/
https://github.com/Rplus/Pokemon-shiny/issues/79
