### ISSUE TITLE
make a clickable link to the cors demo site workaround?

### ISSUE THREAD

**Issue by YesThatAllen** [Rplus/Pokemon-shiny#82]
I'm aware of the #72 link shortener issue, even know i'm supposed to go to 
http://cors-anywhere.herokuapp.com/ for a temp fix

it'd be super cool if we could click a link to it, vs try to read it out of the error message.. I see it in the message below, but on chrome on mac on a desktop, I can't just click this.

![2021-03-14_17-11-22](https://user-images.githubusercontent.com/2879972/111086417-0968aa00-84ea-11eb-9b51-27ead6ca2d25.png)

maybe put a link here? (or, whatever)

![2021-03-14_17-24-13](https://user-images.githubusercontent.com/2879972/111086461-39b04880-84ea-11eb-8469-2f6fa38e6f7d.png)

**Comment by Rplus** [comment]
Does it not open a new page after you click `OK`?

**Comment by Rplus** [comment]
The shorten url issue might be fixed on f06c6688.
