### ISSUE TITLE
Personal checklist disappeared?

### ISSUE THREAD

**Issue by SvartdalDad** [Rplus/Pokemon-shiny#83]
Hi there, and thank you so much for creating the shiny checklist!

However, since yesterday my personal checklist seems to be empty. User name "SvartdalDad". It's a real loss, as I found it very useful. Can you check what happened?

All the best,
SvartdalDad

**Comment by Rplus** [comment]
I never save anyone list on my side.
Check your browser, and my site is https://rplus.github.io/Pokemon-shiny/

**Comment by benyjr** [comment]
iOS has an anti tracking feature that deletes cookies to sites you haven't visited in seven days. Either disable the feature, or share your shiny list url to your notepad app every time you update it.

**Comment by Rplus** [comment]
ref: #92
