### ISSUE TITLE
List gets reset randomly on iOS

### ISSUE THREAD

**Issue by benyjr** [Rplus/Pokemon-shiny#92]
My wife is using the shiny tracking via leekduck.com on iPhone SE and iOS 14.6 and every few months the list gets reset to blank. Even her username is wiped.

I know we can back up the list locally, but it's getting tedious having to recreate the list constantly.

**Comment by Rplus** [comment]
Hello, I'm not a iOS user and sorry I am not sure what is wrong with that.
But I see a post about webkit(Safari engine) "Intelligent Tracking Prevention" feature
> [Full Third-Party Cookie Blocking and More | WebKit](https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/#:~:text=7-Day%20Cap%20on%20All%20Script-Writeable%20Storage)

It says, Safari will reset storage if without user interaction on the website in 7-days.

On the second section, there is a different logic for storage limitation.
If you add the website to HomeScreen, Safari will not reset storage in 7-days.

I'm not sure, but i think you could try to add shiny list into homescreen. :)

**Comment by benyjr** [comment]
That is really good information. We'll try adding the bookmark to the homescreen and see if it solves the problem. Thank you!

**Comment by NukeWorker** [comment]
I use Firefox on Windows 10, and I have the same issue.  It is not exclusive to iOS devices.

**Comment by BartmanEH** [comment]
This is why RPlus worked so hard on the "Get Short URL" feature:
<img width="184" alt="Screen Shot 2022-10-02 at 8 21 58 AM" src="https://user-images.githubusercontent.com/6135879/193453661-b872c861-ba0d-4ed3-9ab1-1c7bb4753de6.png">
Generate a short URL for your list and save it as a bookmark. 100% reliable way to save your list!

**Comment by benyjr** [comment]
Problem exists with cookie retention on the individual platforms.
