### ISSUE TITLE
shiny Corsola

### ISSUE THREAD

**Issue by BartmanEH** [Rplus/Pokemon-shiny#94]
I don’t think shiny Corsola has been released yet:
“ Update: Due to recent developments, we will be postponing the Pokémon Air Adventures collaboration that was scheduled to begin on Thursday, July 22, 2021.”
Source: [https://pokemongolive.com/post/flying-pikachu-2021/](https://pokemongolive.com/post/flying-pikachu-2021/)

**Comment by Rplus** [comment]
Yes, that is mistake for now. I'll remove that. Thanks. : P

**Comment by Rplus** [comment]
removed on 64695b2
